### ISSUE TITLE
The ansible_local var is not being populated when using the setup module to gather custom facts.

### ISSUE THREAD

**Issue by TheRealAlexV** [ansible-collections/ansible.windows#102]
##### SUMMARY
The ansible_local var is not being populated when using the setup module to gather custom facts.

**Playbook:**
```
---
- name: Testing and Debug PB
  hosts: all
  tasks:
  
    - name: Gather Facts
      setup:
        fact_path: 'c:\custom_facts'

    - debug:
        msg: "{{ hostvars[inventory_hostname] }}"

    - debug:
        msg: "{{ ansible_local }}"
```
**Contents of "C:\custom_facts\foo.fact" on remote host:**
```
[general]
asdf=1
bar=2
```

Playbook Output:
```
ansible-playbook -i inv/dev 301_pb_testing.yml -vv
ansible-playbook 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: 301_pb_testing.yml ************************************************************************************************************************************************1 plays in 301_pb_testing.yml

PLAY [Testing and Debug PB] *************************************************************************************************************************************************
TASK [Gathering Facts] ******************************************************************************************************************************************************task path: /home/alex/git.sigma/SDG-Tech-DevOps/ansible/301_pb_testing.yml:2
ok: [demi-win00]
META: ran handlers

TASK [facts : Gather Facts] *************************************************************************************************************************************************task path: /home/alex/git.sigma/SDG-Tech-DevOps/ansible/roles/facts/tasks/main.yml:14
ok: [demi-win00]

TASK [debug] ****************************************************************************************************************************************************************task path: /home/alex/git.sigma/SDG-Tech-DevOps/ansible/301_pb_testing.yml:15

---------REMOVED ALL HOSTVAR OUTPUT FOR BREVITY AND PRIVACY--------

ok: [demi-win00] => 
  msg: |-
    ansible_architecture: 64-bit
    ansible_bios_date: 03/31/2014
    ansible_bios_version: rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org
    ansible_check_mode: false
    ansible_connection: winrm
    ansible_date_time:
  ......
    ansible_facts:
   ......
    ansible_kernel: 10.0.17763.0
    ansible_lastboot: '2020-08-29 11:07:46Z'
    ansible_machine_id: S-1-5-21-49790847-4020553596-361474921
   ......

---------REMOVED ALL HOSTVAR OUTPUT FOR BREVITY AND PRIVACY--------

TASK [debug] ****************************************************************************************************************************************************************task path: /home/alex/git.sigma/SDG-Tech-DevOps/ansible/301_pb_testing.yml:18
fatal: [demi-win00]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'ansible_local' is undefined
  
    The error appears to be in '/home/alex/git.sigma/SDG-Tech-DevOps/ansible/301_pb_testing.yml': line 18, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - debug:
          ^ here
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
setup, custom facts, windows

##### ANSIBLE VERSION

```
ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
```

##### CONFIGURATION

```
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
```

##### OS / ENVIRONMENT

Debian Ansible Controller
Windows Server 2019 Remote

##### EXPECTED RESULTS
I would expect ansible_local to be populated once setup is run over a valid custom fact.

##### ACTUAL RESULTS
It doesn't work.

**Comment by jborean93** [comment]
Have a read of the [setup module's docs](https://docs.ansible.com/ansible/latest/modules/setup_module.html). It states under `fact_path`

> Check notes for Windows options

Under the notes it then has this entry

> If the target host is Windows you can now use fact_path. Make sure that this path exists on the target host. Files in this path MUST be PowerShell scripts (*.ps1) and their output must be formattable in JSON (Ansible will take care of this). Test the output of your scripts. This option was added in Ansible 2.1.

So to be able to use `fact_path` on Windows you need to specify a directory that contains 1 or more `.ps1` scripts which output the facts as json. While this is different behaviour to `setup` on Linux/Python it is how things were originally implemented. Even if this was a feature request to add support for the `ini` format this is not something that will be easily done/accepted. This is because of a few reasons:

* PowerShell/.NET has no native way of parsing the ini format so any implementation would have to be manually implemented.
* The ini format has not strict definition so it's hard to narrow down how to actually support it
    * Should we treat `#` as a comment like Python does or use `;` like Windows expects for it's ini files
* The ini format doesn't handle complex types too well whereas json is a lot more extensible
    * You can do `"{"key": ["array 1", "array 2"], "other": {"nested key": [true]}}` in json quite easily
* The existing setup executes the scripts and reads the output so the data isn't limited to being static and can be dynamically retrieved

As such I am going to close this issue as we have documented the only option that works for `fact_path` on Windows (PowerShell script outputting json) and we have no desire to add support for ini facts.
