### ISSUE TITLE
win_security_policy modifies the encoding of Registry key value

### ISSUE THREAD

**Issue by egvghost** [ansible-collections/ansible.windows#105]
##### SUMMARY

win_security_policy modifies the encoding of Registry key value MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\LegalNoticeText, changing special characters such as french accents into '?'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_security_policy

##### ANSIBLE VERSION

```
ansible 2.9.2
  config file = None
  configured module search path = [u'/Users/egvidal/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/egvidal/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/egvidal/Library/Python/2.7/bin/ansible
  python version = 2.7.16 (default, Jul  5 2020, 02:24:03) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.21) (-macos10.15-objc-
```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT

    target OS: Windows Server 2008
    host OS: MacOS Catalina v10.15.6

##### STEPS TO REPRODUCE

Having 'LegalNoticeText' set in 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' manually set (or via win_regedit module) with a text like:
```
'Vous utilisez un système informatique personnel appartenant à la Société, qui peut être utilisé uniquement aux fins autorisées. En cliquant sur « OK » vous acceptez les conditions d’utilisation.' 
```
after running win_security_policy module to change other settings (not this registry key), the text from this key value changes to:
```
'Vous utilisez un syst?me informatique personnel appartenant ? la Soci?t?, qui peut ?tre utilis? uniquement aux fins autoris?es. En cliquant sur ? OK ? vous acceptez les conditions d?utilisation.'
```

```
  - win_security_policy:
      section: "System Access"
      key: "PasswordComplexity"
      value: "1"
```

##### EXPECTED RESULTS

The expected behavior will be just modify what's expected, without messing up other settings.

##### ACTUAL RESULTS

The setting managed by win_security_policy module changed as expected, but somehow another setting encoding changed too. I assume that's because both are part of the 'security database' handled with secedit..

```paste below

```

**Comment by egvghost** [comment]
I'm still waiting for someone to be assigned to review this issue

**Comment by jborean93** [comment]
Sorry this one must have slipped through. This module is not located in this collection, it's part of the [community.windows](https://github.com/ansible-collections/community.windows) collection.

It's a community supported module so there isn't any guarantee that someone will pick it up in any timeframe. It's up to people in the community to go through the issues and create a fix if they have time. I am technically the maintainer so I might be able to have a look at it sometime but there's no guarantees there.

Closing as the issue should be reported with https://github.com/ansible-collections/community.windows/issues/new?template=bug_report.md.
