### ISSUE TITLE
setup fact_path does not deserialize json in script output

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/ansible.windows#106]
##### SUMMARY
I don't know whether this is a bug or just the behaviour as expected but when using `fact_path` with the `setup` module the fact output is just the json string and not the complex object the json is mean to represent.

If this is decided to be a bug I'm unsure whether we can really fix it as people may be relying on the existing behaviour.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
setup.ps1

##### ANSIBLE VERSION
```paste below
2.8+
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
Create the following file at `C:\Windows\TEMP\facts\my_facts.ps1

```powershell
@{
    my_custom_fact = 'value'
    my_complex_custom_fact = @{
        hello = 'world'
    }
} | ConvertTo-Json -Compress
```

Run the following

```bash
ansible windows -m setup -a fact_path=C:/Windows/TEMP/facts
```

##### EXPECTED RESULTS
The fact is the complex object the json represents

```
"ansible_my_facts": {
    "my_custom_fact": "value",
    "my_complex_custom_fact": {
        "hello": "world"
    }
}
```

##### ACTUAL RESULTS
The fact value is the json as a string

```
"ansible_my_facts": "{\"my_custom_fact\":\"value\",\"my_complex_custom_fact\":{\"hello\":\"world\"}}"
```

**Comment by nitzmahone** [comment]
/me suspects "not a bug" - IIRC the expectation was that the custom fact .ps1 scripts return native objects on the pipeline, not JSON.

**Comment by jborean93** [comment]
Yea I misread the text, it says

> their output must be formattable in JSON

I thought that was saying it must be formatted as JSON not that it just needs to be formattable in JSON. Removing the `| ConvertTo-Json -Compress` did the trick.

I've opened a PR to try and update the docs a bit more https://github.com/ansible/ansible/pull/71791.

**Comment by jborean93** [comment]
Have added some integration tests as well with https://github.com/ansible-collections/ansible.windows/pull/107.
