### ISSUE TITLE
Running setup.ps1 returns ansible_facts but with the ansible_local namespace missing

### ISSUE THREAD

**Issue by IanSJones** [ansible-collections/ansible.windows#108]
##### SUMMARY
Running setup.ps1 returns ansible_facts but with the ansible_local namespace missing

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
lib/ansible/modules/windows/setup.ps1

##### ANSIBLE VERSION
```
ansible --version
ansible 2.9.6
config file = None
configured module search path = ['/home/ukfranke/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible
executable location = /opt/rh/rh-python36/root/usr/bin/ansible
python version = 3.6.9 (default, Nov 11 2019, 11:24:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### CONFIGURATION
```
 ~  /opt/rh/rh-python36/root/usr/bin/ansible-config --only-changed
✘  ~  /opt/rh/rh-python36/root/usr/bin/ansible-config dump --only-changed

Nothing –
```

##### OS / ENVIRONMENT
Windows

##### STEPS TO REPRODUCE
Run the setup module

##### EXPECTED RESULTS
LINUX_HOST | SUCCESS => {
"ansible_facts": {
... lines deleted
"ansible_local": { <--------------------------------- we expect this from the Windows facts
"qurate_facts": {
"hiera": {
"q_app": "RHEL7_REPOS",
"q_cmgm": "NONE",
"q_dc": "HUC",
"q_env": "ITSUPP",
"q_market": "GERMANY",
"q_owner_business": "de-qvc-unix@qvc.com",
"q_owner_support1": "coreeng-linux_unix_engineering-eu@qvc.com",
"q_owner_support2": "de-qvc-unix@qvc.com",
"q_reboot_time": "20:00:00",
"q_role": "DE_RHEL7",
"q_site": "HUC",
"q_used": "true"
}
... lines deleted
"changed": false
}

##### ACTUAL RESULTS

```
WINDOWS_HOST | SUCCESS => {
"ansible_facts": {
... lines deleted
"ansible_qurate_facts": {
"hiera": {
"q_app": "TEST",
"q_cmgm": "NONE",
"q_env": "DEV",
"q_market": "GERMANY",
"q_owner_business": "de-qvc-unix@qvc.com",
"q_owner_support1": "de-qvc-unix@qvc.com",
"q_owner_support2": "de-qvc-unix@qvc.com",
"q_reboot_time": "undef",
"q_role": "undef",
"q_site": "HUC",
"q_used": "undef"
}
},
... lines deleted
},
"changed": false
}


```
I have the fix:
diff /tmp/setup.org /usr/local/lib/python3.6/site-packages/ansible/modules/windows/setup.ps1
20a21
$ result.ansible_facts=@{ansible_local=@{}}
23c24
< $result.ansible_facts.Add("ansible_$(($FactsFile.Name).Split('.')[0])", $out)
> $result.ansible_facts['ansible_local'].Add("$(($FactsFile.Name).Split('.')[0])", $out)

**Comment by jborean93** [comment]
Why are you expecting `ansible_local` to be present? The docs for [setup](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html) do state that Windows does not use it

> NOTE - For windows clients, the results will be added to a variable named after the local file (without extension suffix), rather than ansible_local.

**Comment by jborean93** [comment]
Closing due to the above. While this might be a change in how the Python modules work this is behaviour that we cannot change and what people currently using the feature have written their playbooks around.

**Comment by sebw** [comment]
Consistent namespacing between Linux and Windows would allow to create OS agnostic smart inventories in AWX/Ansible Tower.

**Comment by jakubgs** [comment]
>people currently using the feature have written their playbooks around

This makes no sense. If people are using `ansible_facts.<fact_name>` in their Windows playbooks how it that stopping you from making these facts also available under `ansible_local`, the same way they are under Linux. This inconsistency makes creating platform agnostic setups unnecessarily complex as @sebw mentioned. I see no reason not to also add these gathered facts under `ansible_local` without removing them from `ansible_facts` to not cause incompatibility with existing roles.
