### ISSUE TITLE
Where did win_domain_user go ?

### ISSUE THREAD

**Issue by gvcgael** [ansible-collections/ansible.windows#109]
##### SUMMARY

I'm looking for the version of win_domain_user which contains this merge request :  https://github.com/ansible/ansible/pull/54334

It seems to have been merged on December 2019, but the patch is not included in latest ansible v2.9.13.

I thought I could find it in the collection, but the module is not even included. 

So, did this module got deprecated ? Is there any reason ? 

Anyway, as a workaround I'll use  `win_dsc` and call `ADUser`, but still, this is very surprising.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`win_domain_user`

**Comment by mwtrigg** [comment]
This module is a part of the `community.windows` collection

It's FQCN is `community.windows.win_domain_user`.  For more information, see https://docs.ansible.com/ansible/latest/collections/community/windows/win_domain_user_module.html

**Comment by jborean93** [comment]
See above.
