### ISSUE TITLE
Win_feature install issue

### ISSUE THREAD

**Issue by Expresso31** [ansible-collections/ansible.windows#120]
---
- hosts: windows
  gather_facts: no
  tasks:
    - name: Ping Windows Host 
      win_ping:

    - name: Install Windows services
      ansible.windows.win_feature:
        name: Web-Server
        state: present
    

This is my playbook. This is the error I get *
fatal: [windows]: FAILED! => {"changed": false, "msg": "Failed to install Windows Feature: The target of the specified cmdlet cannot be a Windows client-based operating system."}

**Comment by jborean93** [comment]
What's the Windows version you are targeting?

**Comment by Expresso31** [comment]
Windows 10 pro
2004
OS Build: 19041.572

**Comment by jborean93** [comment]
You can't use the `win_feature` module with Windows 10, hence the error

> The target of the specified cmdlet cannot be a Windows client-based operating system.

`win_feature` uses [ServerManager](https://docs.microsoft.com/en-us/powershell/module/servermanager/?view=winserver2012r2-ps) which is a Windows Server specific module not designed for the client ones.

For the client OS' we have [win_optional_feature](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_optional_feature_module.html) which uses the [DISM](https://docs.microsoft.com/en-us/powershell/module/dism/?view=win10-ps) module that is set to work for both Server and Client based OS'.

**Comment by Expresso31** [comment]
Thanks for the reploy. I will change the OS to a server OS

**Comment by Expresso31** [comment]
On server 2019 I don't get any output. The playbook gets stuck

**Comment by jborean93** [comment]
So just to clarify the behaviour here, we have 2 modules that can be used to manage roles and features; [win_feature](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_feature_module.html) and [win_optional_feature](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_optional_feature_module.html). The `win_feature` module is designed for only Windows Server operating systems as it uses the `ServerManager` module that is only present on those distributions. The `win_optional_feature` uses the DISM module which is present on both the server and client Windows Operating systems. They both use different names to refer to the same features and each of the module uses the name based on the module in use. Here is a quick table that shows you how to get the names you can manage on each module.

| Module | Feature Search |
|-|-|
| win_feature | `Get-WindowsFeature -Name '*Name*' \| Select Name, DisplayName` |
| win_optional_feature | `Get-WindowsOptionalFeature -Online -FeatureName '*Name*' \| Select @{N='Name'; E={ $_.FeatureName }}, DisplayName` |
