### ISSUE TITLE
LCM should be disabled

### ISSUE THREAD

**Issue by bvduijn** [ansible-collections/ansible.windows#128]
https://github.com/ansible-collections/ansible.windows/blob/1fa3956716f8ac47327215ee2a2f263f8d4ef1f6/plugins/modules/win_dsc.ps1#L281

Hi,

According to this site https://devblogs.microsoft.com/powershell/invoking-powershell-dsc-resources-directly/ the Local Configuration Manager (LCM) should be disabled when invoking a DSC config from a 3rd party tool like so:

```
[DscLocalConfigurationManager()]

Configuration LCMSettings {

    Node localhost

    {

        Settings

        {

            RefreshMode = “Disabled”

        }

    }

}

LCMSettings

Set-DscLocalConfigurationManager -Path .\LCMSettings -Verbose
```

I can't find these settings in the win_dsc.ps1. I haven't run into any problems, just wondering if this should be added.

Regards,
Bert

**Comment by jborean93** [comment]
I thought we had documented it in the `win_dsc` docs but obviously not. I don't think disabling LCM is something that the module should be done but rather something we should call out in our docs as a requirement.
