### ISSUE TITLE
win_certificate_store with .pfx causes "An error occurred during encode or decode operation"

### ISSUE THREAD

**Issue by davetapley** [ansible-collections/ansible.windows#132]
##### SUMMARY

When using a `.pfx` file,
which can be successfully installed via [`Import-PfxCertificate`](https://docs.microsoft.com/en-us/powershell/module/pkiclient/import-pfxcertificate?view=win10-ps),
with `win_certificate_store`
causes `"An error occurred during encode or decode operation"`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`ansible.windows.win_certificate_store`

##### ANSIBLE VERSION

```paste below
ansible 2.10.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dave/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dave/.local/lib/python3.6/site-packages/ansible
  executable location = /home/dave/.local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) =  ....
```

##### OS / ENVIRONMENT

Target is Windows Server 2019 Standard over WinRM.

##### STEPS TO REPRODUCE

I obtain the `.pfx` from an Azure Keyvault with [`az keyvault secret download`](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az_keyvault_secret_download).

```yaml
    - name: Copy certificate
      ansible.windows.win_copy:
        src: '{{ certname }}.pfx'
        dest: C:\
      register: certificate

    - name: Import certificate
      ansible.windows.win_certificate_store:
        path: 'C:\{{ certname }}.pfx'
        password: ''
        state: present
        store_location: LocalMachine
```

##### EXPECTED RESULTS

The certificate is successfully imported,
as it would be when running
```
Import-PfxCertificate -FilePath C:\example-com.pfx -CertStoreLocation Cert:\LocalMachine\My\
```

##### ACTUAL RESULTS

```paste below
TASK [Import certificate] ********************************************************************************************************
task path: [...]deploy.yml:117
Trying secret FileVaultSecret(filename='[...]/.vault_pass.txt') for vault_id=default

Using module file /home/dave/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_certificate_store.ps1
Pipelining is enabled.
<10.1.0.5> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO 10.1.0.5
EXEC (via pipeline wrapper)
The full traceback is:
Exception calling "Import" with "3" argument(s): "An error occurred during encode or decode operation.
"
At line:54 char:9
+         $certs.Import($path, $password, $store_flags)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CryptographicException

ScriptStackTrace:
at Get-CertFile, <No file>: line 54
at <ScriptBlock>, <No file>: line 238
fatal: [web_test]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "file_type": "der",
            "key_exportable": true,
            "key_storage": "default",
            "password": "",
            "path": "C:\\example-com.pfx",
            "state": "present",
            "store_location": "LocalMachine",
            "store_name": "My",
            "thumbprint": null
        }
    },
    "msg": "Failed to load cert from file: Exception calling \"Import\" with \"3\" argument(s): \"An error occurred during encode or decode operation.\r\n\"",
    "thumbprints": []
}
```

**Comment by davetapley** [comment]
I can reproduce the error directly with Powershell by running these commands:
https://github.com/ansible-collections/ansible.windows/blob/1fa3956716f8ac47327215ee2a2f263f8d4ef1f6/plugins/modules/win_certificate_store.ps1#L41-L54

⬆️ does beg the question:
Why are we doing all this work when `Import-PfxCertificate` exists?

**Comment by jborean93** [comment]
> Why are we doing all this work when Import-PfxCertificate exists?

`Import-PfxCertificate` was only available on Server 2012 and newer and when this module was written we were supporting server versions all the way back to Server 2008. The other issue is that `Import-PfxCertificate` installs the cert and key into a store directly whereas the current code places it into an in memory X509Certificate2Collection. This allows us to do the idempotency checks and then subsequently store it into the requested store/location if necessary.

Is your `.pfx` a binary file or is is a PEM encoded cert with a key? I'm seeing some reports where `.Import` fails when trying to import a PEM encoded pfx and the workaround is the convert it to bytes manually which is what we do when outputting the file https://github.com/ansible-collections/ansible.windows/blob/1fa3956716f8ac47327215ee2a2f263f8d4ef1f6/plugins/modules/win_certificate_store.ps1#L133.

**Comment by davetapley** [comment]
Thanks for the fast reply @jborean93 🙏🏻 

` Get-CertFileType` blows up before it even gets to that line, here: 
```
$certs.Import($path, $password, 0)
Exception calling "Import" with "3" argument(s): "An error occurred during encode or decode operation.
```

I looked closer at the `.pfx` I was using and I'm not actually sure what it is 😑 
If I do [`file -b --mime-type`](https://unix.stackexchange.com/a/275530/10861) I get `text/plain`, so not binary, but not sure if 'PEM encoded cert with a key' either.
The contents appears to be just a random string of characters, starting `MIIRUAIBAz` and ending `CB9A=`.

---

`az keyvault secret download` takes an optional [`--encoding`](https://docs.microsoft.com/en-us/cli/azure/keyvault/secret?view=azure-cli-latest#az_keyvault_secret_download-optional-parameters), so I played around with that:

* `utf-8` (the default) and `ascii` both output the same `.pfx` file
* `hex` caused an error (see https://github.com/Azure/azure-cli/issues/16031)
* `base64` produced a `application/octet-stream` which **worked** with `win_certificate_store` 🎉 

---

So I'm happy with using `--encoding base64` as a solution and close, unless you think there's merit in digging in to what exactly what the default/`utf-8`/`ascii` encoding is all about?

**Comment by jborean93** [comment]
> The contents appears to be just a random string of characters, starting MIIRUAIBAz and ending CB9A=.

So it's definitely base64 encoded but hard what part is actually base64 encoded. I'll probably have to create my own secret and download the key to try it out. If `Import-PfxCertificate` works then obviously it's possible to load into Windows, we just need to figure it out.

> So I'm happy with using --encoding base64 as a solution and close

I'll probably keep this open for now. It's good that there's a working solution but sounds like this module could still handle the other scenario as well.

**Comment by jborean93** [comment]
I finally got round to investigating this, it turns out the `--encoding` option on `az keyvault secret download` does not correspond to the format of the file created. It is rather meant to refer to the format of the source file so it can translate the string value into bytes when it creates the file. For non-certificate secrets I can see why things like `ascii`/`utf-8`/`utf-16le` would matter but for a cert it is stored as a base64 encoded value.

So when specifying `--encoding utf-8/ascii` it will just download the secret as is which is the base64 value you see without any of the headers or trailers that .NET expects. When you specify `--encoding base64` it will base64 decode the secret data and place that into the file. Ultimately this is the actual cert bytes so it makes sense why `win_certificate_store` works with that.

A very confusing option from `az cli` and I personally don't think the fix for https://github.com/Azure/azure-cli/issues/11084 really made it simpler to understand.

So to fix this we could technically try and add the header/trailer to the source contents before loading but I personally don't think that is a good idea for 2 reasons:

* It makes the code more complex
  * We now need to detect if the contents is a base64 value without the headers
  * Currently we rely on .NET doing all this hard work and it would be nice to keep things that way
* There is a simple workaround - i.e. download the raw bytes with `--encoding base64` and use that
  * While hardly noticeable the downloaded file will be smaller so it's technically more efficient to transfer across

Thanks for the great information you shared to help get down to the bottom of this.
