### ISSUE TITLE
Ansible IP target uses system proxy since 2.10 and fails to connect

### ISSUE THREAD

**Issue by Nimrod-666** [ansible-collections/ansible.windows#139]
##### SUMMARY
Ansible since 2.10 seems to try to go through system proxy to connect to winrm targets by ip. That was not an issue in 2.9

E.g. 

My target is a IP "10.175.244.50". The ip is not part of the noproxy environment variable on the ansible server.
I try to connect to the windows target with these settings:
`
ansible_user: ansibleuser
ansible_connection: winrm
ansible_winrm_cert_pem: /root/.ssh/winkey/xxx.pem
ansible_winrm_cert_key_pem: /root/.ssh/winkey/xxx_key.pem
ansible_winrm_transport: certificate
ansible_winrm_server_cert_validation: ignore
ansible_winrm_scheme: https
`

Now any playbook run already fails at the gathering facts section:

`
TASK [Gathering Facts] ********************************************************************************************************************************************************************
[WARNING]: packaging Python module unavailable; unable to validate collection Ansible version requirements
fatal: [10.175.244.50]: UNREACHABLE! => {"changed": false, "msg": "certificate: HTTPSConnectionPool(host='10.175.244.50', port=5986): Max retries exceeded with url: /wsman (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))", "unreachable": true}
`

- When i add 10.175.244.50 variable to /etc/environment ->no_proxy -> it works
- The problem is only on windows hosts. SSH connection to linux is no problem. The proxy is not used then.
- The problem exists since ansible-server 2.10

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
winrm connector

##### ANSIBLE VERSION

```
ansible 2.10.3
  config file = /root/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION

```
DEFAULT_VAULT_PASSWORD_FILE(/root/ansible.cfg) = /scheer/.vault_pass.txt
HOST_KEY_CHECKING(/root/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ubuntu 18.04 for server. Current ansible version.
Target is Windows Server 2019

##### STEPS TO REPRODUCE
- use an ip and not an hostname as target
- setup a proxy on ansibles server os and don't add your target to no_proxy
- try to connect to target with ansible winrm certificate connection

##### EXPECTED RESULTS
Successfull connection

##### ACTUAL RESULTS
Timeout because my proxy can't reacht the target. A direct connection would work.

**Comment by jborean93** [comment]
Ansible doesn't control the actual connection that is set up for the Windows host and in your case it's calling the [pywinrm](https://github.com/diyan/pywinrm) library that manages all this. There are quite a few things at play when it comes to selecting the proxy and I believe the 0.4.0 release changed a few things there. Another part that could be at play is the version of `requests` which is what pywinrm uses to make the actual connection. There could have been a change in behaviour with that version or a regression recently introduced.

If you do have pywinrm 0.4.0 installed your best bet is to set `ansible_winrm_proxy: ~` (sets to None) to tell pywinrm that you don't want to use a proxy at all, even if there is an env var present.
