### ISSUE TITLE
RFE: Modify permissions of private keys in the certificate store

### ISSUE THREAD

**Issue by opoplawski** [ansible-collections/ansible.windows#150]
##### SUMMARY
I need a way to modify the permissions of a private key in the computer certificate store - specifically to give a local group read access.  We looking into using computer certificates for OpenVPN authentication and the user (via the OpenVPN Administrators group) needs to be able to use the key.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_certificate_store

**Comment by jborean93** [comment]
There's a PR to add support for this to `win_acl` https://github.com/ansible-collections/ansible.windows/pull/94 but right now it needs some tests before I would consider merging it.
