### ISSUE TITLE
Add a module for connecting and authenticating for RDP session

### ISSUE THREAD

**Issue by sugitk** [ansible-collections/ansible.windows#164]
##### SUMMARY

Like `win_ping`, a user wants to see whether the RDP is able to be accepted or not.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

- Check 3389/tcp port is open 
- Authenticate according to its inventory with the suitable authenticate method (NTLM, Kerberos, and others)
- Confirm the RDP session is established and ready to operate

**Comment by jborean93** [comment]
While this is a nice idea it's not something we are planning on working on anytime soon. You can already achieve the first 2 with `win_wait_for` and `become` (to test the logon) but the latter and putting it all together will be quite hard. You are more than welcome to create a PR in [community.windows](https://github.com/ansible-collections/community.windows) if you do have an action plugin that does this for you but right now it's not something we plan to implement or even support in `ansible.windows`.
