### ISSUE TITLE
Failed to invoke DSC Set method: PowerShell DSC resource MSFT_xCluster

### ISSUE THREAD

**Issue by romilgupta28** [ansible-collections/ansible.windows#177]
- name: WSFC | Add a powershell module on {{ wsfc_primary_server }}
  win_psmodule:
    name: xFailOverCluster
    state: present
- name: WSFC | Add windows features on {{ wsfc_primary_server }}
  win_dsc:
    resource_name: WindowsFeature
    Name: "{{ item }}"
    Ensure: Present
  loop: "{{ wsfc_required_features }}"
- name: WSFC | Install Failover-Clustering feature with Management Tools on {{ wsfc_primary_server }}
  win_feature:
    name: Failover-Clustering
    state: present
    include_management_tools: yes
  register: wsfc_primary_feature

    name: WSFC | Create Windows Cluster {{ wsfc_cluster_name }} on Primary Server {{ wsfc_primary_server }}
    win_dsc:
    resource_name: xCluster
    name: "{{ wsfc_cluster_name }}"
    staticipaddress: "{{ wsfc_cluster_ip_address }}"
    domainadministratorcredential_username: "{{ wsfc_domain_admin_username[win_environment] }}@{{ wsfc_dns_domain_name }}"
    domainAdministratorcredential_password: "{{ wsfc_domain_admin_password[win_environment] }}"
    register: create_windows_cluster

Error in last task:

[[xCluster]DirectResourceAccess] If you are running Windows PowerShell remotely, note that some failover clustering cmdlets do not
work remotely. When possible, run the cmdlet locally and specify a remote computer as the target. To run the cmdlet remotely, try using the Credential Security Service Provider (CredSSP).
All additional errors or warnings from this cmdlet might be caused by running it remotely.

fatal: []: FAILED! => {"changed": false, "module_version": "1.14.1", "msg": "Failed to invoke DSC Set method: PowerShell DSC resource MSFT_xCluster failed to execute Set-TargetResource functionality with error message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Static network <<>> was not configured. Please use -StaticAddress to use this network or use -IgnoreNetwork to ignore it. ", "reboot_required": false}

wsfc_required_features:

    Failover-Clustering
    RSAT-Clustering-PowerShell
    RSAT-Clustering-CmdInterface

**Comment by jborean93** [comment]
This is a bug in the `MSFT_xCluster` resource, the `win_dsc` module simply calls the set method for that resource and DSC goes to execute it. The error is saying that some internal code failed because it set `$ErrorActionPreference = 'Stop'` and it's call to some cmdlet didn't set `-StaticNetwork` or `-IgnoreNetwork`. There's nothing we can do about that and you will need to open the issue with that DSC resource.
