### ISSUE TITLE
ansible_date_time.epoch still broken and still inconsistent to other plattforms

### ISSUE THREAD

**Issue by quindar83** [ansible-collections/ansible.windows#183]
##### SUMMARY
The value in ansible_date_time.epoch is inconsistent, depending on the plattform.
This is a follow up to https://github.com/ansible/ansible/issues/72479, which didn't fix the issue. 

- Linux systems return an int
- Mac systems return an int
- en_us Windows systems return a float and you need to use | int to use it
- de_de Windows systems return an string with a comma and using | int will cause it to be 0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.builtin.setup

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /home/ansible/.ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/venv-ansible/lib/python3.6/site-packages/ansible
  executable location = /home/ansible/venv-ansible/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
DEFAULT_ASK_PASS(/home/ansible/.ansible.cfg) = False
DEFAULT_BECOME(/home/ansible/.ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/ansible/.ansible.cfg) = False
DEFAULT_BECOME_METHOD(/home/ansible/.ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/ansible/.ansible.cfg) = root
DEFAULT_HOST_LIST(/home/ansible/.ansible.cfg) = ['/home/ansible/inventory']
DEFAULT_MANAGED_STR(/home/ansible/.ansible.cfg) = This file is managed by Ansible
DEFAULT_REMOTE_USER(/home/ansible/.ansible.cfg) = ansible_worker
DEFAULT_VAULT_PASSWORD_FILE(/home/ansible/.ansible.cfg) = /home/ansible/vault.pw
HOST_KEY_CHECKING(/home/ansible/.ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
$ ansible <Windows 10 Pro 20H2 de_de host> -m setup | grep -i epoch
            "epoch": "1613488812,78528",
            "epoch_int": 0,
            "epoch_local": "1613492412,78528",

$ ansible <Windows Server 2019 x64 en_us host> -m setup | grep -i epoch
            "epoch": "1613488778.40655",
            "epoch_int": 0,
            "epoch_local": "1613492378.40655",

$ ansible <CentOS 8 host> -m setup | grep -i epoch
             "epoch": "1613488700",

$ ansible <MacOS 10.15 host> -m setup | grep -i epoch
             "epoch": "1613488993",
```

##### EXPECTED RESULTS

ansible_date_time.epoch should always contain an integer

##### ACTUAL RESULTS

see above.

**Comment by jborean93** [comment]
So while there is a bug with `epoch_int` where it's using an undefined variable causing the value to become `0` which needs to be fixed we cannot change `epoch` to match the Linux facts due to backward compatibility concerns. Doing so would cause anyone that has playbooks that rely on `epoch` for Windows being in a culture specific format and that's why `epoch_int` was added. I need to figure out whether `epoch` on Linux is based on the universal (UTC) or local time but once I do the fix for `epoch_int` is trivial.

**Comment by jborean93** [comment]
The PR https://github.com/ansible-collections/ansible.windows/pull/184 fixes this problem. The `epoch` value is still the original culture specific format but `epoch_int` will return the seconds since epoch (as an integer not string).
