### ISSUE TITLE
 win_updates module does not update the servers "last installed updates" date after patching windows server 2012/16/19. 

### ISSUE THREAD

**Issue by ammygill** [ansible-collections/ansible.windows#187]
#### SUMMARY
--> Windows Server Enterprise x64, 2012, 2016, 2019 using Ansible Engine 2.9.17.
After patching via ansible the last installed updates date is not changes but the system is updated. Even after doing multiple manual reboots, it shows the old date only..

##### ISSUE TYPE
- Bug Report

##### EXPECTED RESULTS
--> last installed updates must show the latest date.

##### ACTUAL RESULTS
--> It shows the old date after updating the windows server by ansible.

**Comment by jborean93** [comment]
Where are you getting this last installed updates date? Is it somewhere in the GUI or some other registry key.

**Comment by ammygill** [comment]
1 Open Server Manager Dashboard
2 Click on Local Server - notice the Last installed updates date. I see 9/29/2020(date didn't get updated) for todays server
3 On the same dashboard screen, click on the link beside Windows Update - " Download updates only, ...
4 The update history for today shows one KB installed 3/17/2021(latest date)

**Comment by jborean93** [comment]
Thanks for the info, I can replicate the problem but I don't believe this is something we can do much about. There are even reports about other MS tools suffering from the same problem like https://social.technet.microsoft.com/Forums/en-US/812eef00-bdef-4c8d-a8ea-1d4424f1941e/software-updates-does-not-change-last-update-install-date-in-windows-update?forum=ConfigMgrCompliance. Ultimately we are calling the official API to automate this kind of work and if that's failing to set the timestamp that server manager is relying on then IMO it's a bug on them.

For us to "fix" this problem we would have to track down the location where server manager is looking for this and modify that value. It's most likely going to be stored in the registry somewhere which makes me ever more reluctant to have `win_updates` also modify that. Luckily there is a better and automated way to get this last install time using PowerShell:

```powershell
(Get-HotFix | Measure-Object -Maximum InstalledOn).Maximum
```

**Comment by Leo-hanosl** [comment]
We still have this issue. did u find a solution to it?
