### ISSUE TITLE
Cannot use 'name' as a variable name

### ISSUE THREAD

**Issue by fabricat** [ansible-collections/ansible.windows#198]
##### SUMMARY

When I run `ansible -m ansible.windows.win_service_info` I'd like to specify the `name` parameter, as described on [win_service_info.py](https://github.com/ansible-collections/ansible.windows/blob/fd71f3276d58abb5d8e7b7900e655da631adb1c4/plugins/modules/win_service_info.py#L14)

Unfortunately, it results that `name` is **not a valid name** (since it is **reserved**), thus it is ignored.
It seems that I have no way to limit/filter the service list, when using the module directly from the command line.

I could not find an official list of reserved names, but I found that 'name' **is** a reserved [playbook keyword](https://docs.ansible.com/ansible/devel/reference_appendices/playbooks_keywords.html) (see also https://github.com/ansible/ansible/issues/37836).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_service_info

##### ANSIBLE VERSION

```paste below
ansible 2.9.19
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.8/site-packages/ansible
  executable location = /home/user/.local/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_SSH_ARGS(/home/user/.ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=no
CACHE_PLUGIN(/home/user/.ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/user/.ansible.cfg) = /tmp/ansible_cachedir
CACHE_PLUGIN_TIMEOUT(/home/user/.ansible.cfg) = 86400
DEFAULT_BECOME(/home/user/.ansible.cfg) = True
DEFAULT_GATHERING(/home/user/.ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/user/.ansible.cfg) = ['/home/user/ansible/inventory-shared/static']
HOST_KEY_CHECKING(/home/user/.ansible.cfg) = False
INTERPRETER_PYTHON(/home/user/.ansible.cfg) = auto_silent
INVENTORY_CACHE_ENABLED(/home/user/.ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/home/user/.ansible.cfg) = jsonfile
INVENTORY_CACHE_PLUGIN_CONNECTION(/home/user/.ansible.cfg) = /tmp/ansible_inventory
TRANSFORM_INVALID_GROUP_CHARS(/home/user/.ansible.cfg) = always
```

##### OS / ENVIRONMENT

Ubuntu 20.04 in WSL2 on Control node.
Target node is irrelevant.

##### STEPS TO REPRODUCE

```
ansible -m ansible.windows.win_service_info --ask-pass -e '{"name":"Zabbix agent"}' test-win01.local
```

##### EXPECTED RESULTS

I expected to get info only for the "Zabbix agent" service.

##### ACTUAL RESULTS

I get the following warning:

```paste below
[WARNING]: Found variable using reserved name: name
```
Then I get info about **all** the services on the remote host.

**Comment by jdelaporte** [comment]
Hello! You can pass module options with -a (arguments) rather than -e (extra vars). 

Dudes the following work for you: 

ansible test-win01.local -m ansible.windows.win_service_info -a '{"name":"Zabbix agent"}'  --ask-pass

**Comment by fabricat** [comment]
That's correct... it works!

Sorry, I am going lost in Ansible documentation :) 
Thank you for your kind support.

**Comment by jdelaporte** [comment]
I am glad to hear it! You're welcome.

Joanna Delaporte
