### ISSUE TITLE
win_domain_membership: Error changing hostname

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/ansible.windows#20]
_From @dagwieers on Oct 30, 2018 13:54_

##### SUMMARY
When running our configuration script with Ansible v2..8 (devel branch) on 4 new Windows 10 laptops resulted in the below error:

```
TASK [Configure hostname, domain and workgroup] ********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 300
fatal: [computer113]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Skip computer 'computer113' with new name 'computer113' because the new name is the same as the current name."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 300
fatal: [computer115]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Skip computer 'computer115' with new name 'computer115' because the new name is the same as the current name."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 300
fatal: [computer116]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Skip computer 'computer116' with new name 'computer116' because the new name is the same as the current name."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 300
fatal: [computer114]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Skip computer 'computer114' with new name 'computer114' because the new name is the same as the current name."}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_domain_membership

##### ANSIBLE VERSION
```
ansible 2.8.0.dev0 (msc_user 91f86f51a6) last updated 2018/10/30 01:36:49 (GMT +200)
  config file = /home/dag/home-made/crombeen/ansible.cfg
  configured module search path = [u'/home/dag/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/anvers/default/lib/ansible
  executable location = /opt/anvers/default/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

_Copied from original issue: ansible/ansible#47810_

**Comment by jborean93** [comment]
_From @dagwieers on Oct 30, 2018 20:21_

So the issue seems to be that the system was not yet rebooted. So maybe **win_domain_membership** should be returning OK/changed with a warning instead of failing to guarantee idempotency.

**Comment by progSides** [comment]
I am getting the error too.  It would be nice to have this be idempotent as described.  I'll take a quick look.

**Comment by progSides** [comment]
> I am getting the error too. It would be nice to have this be idempotent as described. I'll take a quick look.

EDIT1: It looks like this might be due to names that are longer than 15 characters and causing a prompt in PowerShell "The NetBIOS name will be truncated. Do you wish to continue?".  It looks like someone may have already thought of something for this: https://github.com/ansible-collections/ansible.windows/blob/8f8f6182f358a89316e18e7cfd4eaf17f9fa69c2/plugins/modules/win_domain_membership.ps1#L33

**Comment by progSides** [comment]
> > I am getting the error too. It would be nice to have this be idempotent as described. I'll take a quick look.
> 
> EDIT1: It looks like this might be due to names that are longer than 15 characters and causing a prompt in PowerShell "The NetBIOS name will be truncated. Do you wish to continue?". It looks like someone may have already thought of something for this:
> 
> https://github.com/ansible-collections/ansible.windows/blob/8f8f6182f358a89316e18e7cfd4eaf17f9fa69c2/plugins/modules/win_domain_membership.ps1#L33

I'm trying to submit a PR, but getting a 403.  Will have to try more tomorrow.

**Comment by jborean93** [comment]
Please try out [microsoft.ad.membership](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/membership_module.html#ansible-collections-microsoft-ad-membership-module) instead. I put in a lot of work to try and solve a lot of the hostname changes as it screws up the state of the host in a lot of ways that makes it hard to reconnect. The `win_domain_membership` module is going to be deprecated soon in favour of the one in `microsoft.ad` very soon.

**Comment by jborean93** [comment]
The PR https://github.com/ansible-collections/ansible.windows/pull/507 has deprecated the `win_domain` module in this collection in favour of [microsoft.ad.membership](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/membership_module.html#ansible-collections-microsoft-ad-membership-module) in the [microsoft.ad collection](https://github.com/ansible-collections/microsoft.ad). This collection contains various domain utilities in one common collection that is supported by myself and is part of Red Hat's Automation Platform supported collections.

The `microsoft.ad.membership` module was essentially a copy of `win_domain_membership` from this repository but was rewritten to better support scenarios like hostname renames during a domain join. It also supports a `reboot: true` option to automatically reboot the host within the module itself avoiding some of the common problems seen with trying to reboot after. I recommend you give this module a try as it should fix the problems reported here.

If it still has problems then opening an issue on the [microsoft.ad collection](https://github.com/ansible-collections/microsoft.ad) is recommended.
