### ISSUE TITLE
win_domain: FUTURE: Any sane way to do the detection under check-mode *without* installing the feature?

### ISSUE THREAD

**Issue by rgl** [ansible-collections/ansible.windows#206]
Can the following code be modified for not installing the feature by calling Get-MissingFeatures instead of Install-Prereqs?

https://github.com/ansible-collections/ansible.windows/blob/6f8cfa39a9a0213be63cb167d9880c8feb14508d/plugins/modules/win_domain.ps1#L100-L101

**Comment by jborean93** [comment]
The function this is referring to calls this https://github.com/ansible-collections/ansible.windows/blob/6f8cfa39a9a0213be63cb167d9880c8feb14508d/plugins/modules/win_domain.ps1#L37

We've added `-WhatIf:$check_mode` which means it is telling the `Add-WindowsFeature` to run normally but don't actually make any changes, just like how our check mode works. The `FUTURE` part is referring to the fact that if the required pre-requisites aren't installed we cannot actually detect if a domain needs to be created or not. Right now if you are in check mode and the features are installed the module will exit early stating a change has happened but in reality it hasn't actually checked if the domain is present.

Are you seeing any different behaviour here or just saw the `FUTURE` note?
