### ISSUE TITLE
Galaxy release with the win_powershell module?

### ISSUE THREAD

**Issue by rgl** [ansible-collections/ansible.windows#213]
I would like to use the [`win_powershell`](https://github.com/ansible-collections/ansible.windows/blob/main/plugins/modules/win_powershell.py) module but it seems the https://github.com/ansible-collections/ansible.windows/releases/tag/v1.5.0 release on this repository was not published to https://galaxy.ansible.com/community/windows.

Do you have any idea why this happened?

Or better yet, can you please make a galaxy release? :-)

**Comment by jborean93** [comment]
This repo is for the [ansible.windows](https://galaxy.ansible.com/ansible/windows) collection and the v1.5.0 release is published there for you to use right now (as of 12 days ago).

**Comment by rgl** [comment]
Oh my bad... sorry... for some reason I though those two modules were the same.

Now with your `win_powershell` [things now seem simpler to me (`$Ansible.Changed` replaces `register/changed_when`)](https://github.com/rgl/terraform-libvirt-ansible-windows-example/commit/deca3daec03f90de2e7833b3be3c9b3c12bcca17). Thank you :-)

BTW, from my initial feeling, it seems `$Ansible.Changed = $false` should have been the default value for the `Changed` property. But I guess that boat as already sailed.
