### ISSUE TITLE
win_updates filtered_reason change to an array of reasons

### ISSUE THREAD

**Issue by agibson2** [ansible-collections/ansible.windows#226]
##### SUMMARY
Currently win_updates has a few reasons why an update is not installed.  The code will only populate filtered_reason with the first reason that gets processed.  This can be misleading if you add a new filter (blacklist, skip_hidden, etc) and it shows a different reason that is is filtered.

##### ISSUE TYPE
If an update is being filtered, you do not get a full set of reasons why an update is filtered.  Troubleshooting why an update isn't being installed is a little more difficult because the reason stated might not be the only reason an update is being filtered.   You have to experiment by fixing the first reason and the running it again to find the next reason it is being filtered.

##### COMPONENT NAME
win_updates

##### ADDITIONAL INFORMATION
If filtered_reason was an array, It could be populated with multiple reasons why an updated was filtered (category, skip_hidden, blacklist, etc).  This would make troubleshooting why an update isn't being installed much easier because you would see all reasons an update is not being applied instead of only the first reason it was filtered.

The code currently uses 'continue' when it hits the first condition that filters an updates.  This would need to be changed to not break out of the rest of the checks for filtering and add the reason to an array.  After all the checks are done, it would then need to see if the update was filtered and break of the rest of the code using 'continue' at that point.

**Comment by jborean93** [comment]
We cannot change the format of `filtered_reason` without breaking any existing playbooks that rely on the string behaviour. In saying that I'm refactoring the `win_updates` module right now and have added a `filtered_reasons` return value and deprecated the current single value `filtered_reason` value which will give you want you are wanting. The PR for this is https://github.com/ansible-collections/ansible.windows/pull/225

**Comment by agibson2** [comment]
Thanks.  This feature will be helpful in troubleshooting why an update isn't be applied when there are multiple reasons.
