### ISSUE TITLE
Change the primary DNS suffix of this computer

### ISSUE THREAD

**Issue by gabrielviegas** [ansible-collections/ansible.windows#234]
Hey guys.

I have two questions about using Ansible with Windows

1. How to enable Administrator user with Ansible for Windows?

2. How to change the primary DNS suffix of this computer using Ansible for Windows?

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on `irc.libera.chat <https://libera.chat/>`_
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

Regarding your questions 1. probably is with the [win_user](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_user_module.html) module but the question is a bit vague. You might have more luck trying to rephrase the question and elaborate what you want exactly. 2. I don't believe there's a builtin module that can do this, usually it means you want to find a DSC resource and use it with `win_dsc` or find the PowerShell way to put it in a `win_shell` task.
