### ISSUE TITLE
win_wait_for: 'connect_timeout' parameter is not working to check the status of WinRM

### ISSUE THREAD

**Issue by Udayendu** [ansible-collections/ansible.windows#236]
##### SUMMARY
- While using **win_wait_for** module, **connect_timeout** parameter is unable to check the status of WinRM during the windows reboot

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- win_wait_for

##### ANSIBLE VERSION

```
$ pip3 show ansible
Name: ansible
Version: 3.4.0
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.8/dist-packages
Requires: ansible-base
Required-by:

$ pip3 show ansible-base
Name: ansible-base
Version: 2.10.9
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.8/dist-packages
Requires: PyYAML, packaging, jinja2, cryptography
Required-by: ansible

$ pip3 show pywinrm
Name: pywinrm
Version: 0.4.2
Summary: Python library for Windows Remote Management
Home-page: http://github.com/diyan/pywinrm/
Author: Alexey Diyan
Author-email: alexey.diyan@gmail.com
License: MIT license
Location: /usr/local/lib/python3.8/dist-packages
Requires: requests-ntlm, xmltodict, six, requests
Required-by:
```

##### CONFIGURATION
- inventory configuration
```
[windows]
xxx.xxx.xxx.xxx

[windows:vars]
ansible_connection=winrm
ansible_user=domadmin
ansible_password=xxxxxxxxxxxxxxx
ansible_winrm_transport=credssp
ansible_winrm_server_cert_validation=ignore
ansible_port=5986
```

- ansible play
```
- name: winrm port status
  win_wait_for:
    port: 5986
    state: started
    timeout: 600
    sleep: 5
    connect_timeout: 60
```

##### OS / ENVIRONMENT
- Ubuntu 20.04.2 LTS

##### STEPS TO REPRODUCE
- WinRM based connection is used to make the guest os level changes like installing packages, applying patches
- some time OS needs to be rebooted before applying next ansible play
- but while rebooting, the connection check is not happening and playbook execution is failing 

##### EXPECTED RESULTS
- It should wait as per the value defined for the module using **connect_timeout** parameter to allow WinRM to get ready

##### ACTUAL RESULTS
- Instead of waiting, immediately with in 5-10 secs its giving the following exception:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='x.x.x.x', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc79e1f53d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
fatal: [x.x.x.x]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```

OR

```
fatal: [x.x.x.x]: UNREACHABLE! => {"changed": false, "msg": "credssp: HTTPSConnectionPool(host='x.x.x.x', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5ea6731b20>: Failed to establish a new connection: [Errno 111] Connection refused'))", "unreachable": true}
```

OR

```
fatal: [x.x.x.x]: UNREACHABLE! => {"changed": false, "msg": "credssp: HTTPSConnectionPool(host='x.x.x.x', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9f1c2cbac0>, 'Connection to x.x.x.x timed out. (connect timeout=30)'))", "unreachable": true}
```

**Comment by 4smirnovsn** [comment]
Make sure that 5986 port is opened in Windows Firewall on target host. For example you can try to connect from ansible host to windows host: telnet windows.ip.address 5986

**Comment by Udayendu** [comment]
> 
> 
> Make sure that 5986 port is opened in Windows Firewall on target host. For example you can try to connect from ansible host to windows host: telnet windows.ip.address 5986

port is open and its working as well. But if the system is rebooting after performing a task, then immediately its loosing the connection. And the **win_wait_for** module is not helping to get response for WinRM connection.

**Comment by jborean93** [comment]
The `win_wait_for` module is a module that runs on the target Windows host, like `win_ping`, `win_file`, etc. It needs to be able to connect just like any other Windows module so if the WinRM endpoint isn't online then it's going to fail. It is designed to check if the Windows host that is being targeted waits for a port it can connect to is online.

What it sounds like you want is `[wait_for_connection](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_connection_module.html) which runs from the Ansible controller to wait until Ansible can actually connect to the host. You could even use [wait_for](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_module.html) with `delegate_to: localhost` to replicate the same behaviour as `win_wait_for` but from the context of the Ansible controller.
