### ISSUE TITLE
win_stat should return UTC time for creationtime/lastaccesstime/lastwritetime

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible-collections/ansible.windows#240]
##### SUMMARY

In win_stat (and setup) module, it returns `creationtime / lastaccesstime / lastwritetime`  in unixtime format. But if the Windows node is JST(UTC +9) timezone, those time added 9h. So when I convert it with `strftime` filter, there is extra 9h because strftime expected the unixtime is in UTC.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- win_stat

##### ANSIBLE VERSION

```
[root@tower win_test]# ansible --version
ansible 2.9.20
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

##### CONFIGURATION

Default

##### OS / ENVIRONMENT

- RHEL8 (Control Node)
- Windows Server 2019

##### STEPS TO REPRODUCE

1. Set the timezone in JST(UTC+9) in Control node and Managed node(Windows).
2. Run the win_stat module and convert it with strftime filter
```
   - win_stat:
       path: C:\Users\Administrator\Desktop\test.txt
     register: result
   - debug: msg="creationtime is {{ '%Y/%m/%d %H:%M:%S' | strftime(result.stat.creationtime) }}"
```

I can see the same behavior in `ansible_date_time.epoch` that gathered by setup module. 
```
   - debug:
       msg: "Current local timezone time: {{ '%Y-%m-%d %H:%M:%S %Z' | strftime(ansible_date_time.epoch) }}"
   - win_shell: date
```

It also added extra 9h if the managed node and control node is in JST.
```
TASK [debug] *******************************************************************
task path: /var/lib/awx/projects/win_test/test.yml:12
ok: [192.168.100.248] => {
    "msg": "Current local timezone time: 2021-06-23 18:51:26 JST"
}

TASK [win_shell] ***************************************************************
    "stdout": "2021-06-23 9:51:32",
```

I cannot see the similar behavior in Linux modules and setup module for Linux since those modules return unixtime in UTC. So I'm assuming this is bug and we need to ignore local timezone when calculate the unixtime in the module.

##### EXPECTED RESULTS

Returned unixtime in UTC.

##### ACTUAL RESULTS

Returned unixtime in local timezone.

**Comment by jborean93** [comment]
I need to look into the code but I do agree we should probably return the UTC offset here. This is not going to be easy to implement though as we have no way of knowing if someone relies on the current time zone dependent value that it's returning. This may be bad enough to warrant the breaking change though.

**Comment by jborean93** [comment]
Thanks for the report, I've just merged https://github.com/ansible-collections/ansible.windows/pull/242 which fixes this problem. Should be present in the next collection release.
