### ISSUE TITLE
setup: Windows Setup wrong epoch timestamp (get-date prints epoch + local_tz)

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/ansible.windows#26]
_From @mkayontour on Sep 09, 2019 12:10_

##### SUMMARY
Running the module setup on Windows prints the wrong epoch timestamp. 
https://github.com/ansible/ansible/blob/a95f9c66401e99e72a12cb9d3a6d6c828bc1ecfe/lib/ansible/modules/windows/setup.ps1#L175 

```
PS C:\Users\ansible> get-date

Montag, 9. September 2019 14:06:33


PS C:\Users\ansible> get-date -UFormat %s
1568038002,68659
```

Windows prints the seconds since 1970 with the local timezone added. 

```
[vagrant@ansible ~]$ date
Mon Sep  9 12:07:14 UTC 2019
[vagrant@ansible ~]$ date +%s
1568030842
# epoch Timestamp from windows without nanoseconds
[vagrant@ansible ~]$ date -d @1568038002  
Mon Sep  9 14:06:42 UTC 2019
```

This issue is already known to powershell and it will be fixed in powershell version 6. 
See [Issue#2195](https://github.com/PowerShell/PowerShell/issues/2195)

In addition the nanoseconds aren't necessary to the epoch timestamp and so it shouldn't be used anymore. 

###### Possible Solution

To get the most accurate result as in the powershell bug described, get-date should be used like this. This is rounded and without nanoseconds 
`[int][double]::Parse((get-date ([DateTime]::UtcNow) -UFormat +%s))`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Module setup on windows 
##### ANSIBLE VERSION
Any

##### OS / ENVIRONMENT
Windows with Powershell version < 6.x 

_Copied from original issue: ansible/ansible#61990_

**Comment by xenlo** [comment]
Hi @jborean93,

I give a try to your fix #73, but still get the same error: `msg: Invalid value for epoch value (1597253655.92744)` when I try to use it with `strftime`.

I tried by installing the 'ansible.windows' collection via `ansible-galaxy` but also by 'git cloning' the master branch into my virtualenv and get the same result.

Maybe it's due to some version stuff on the remote windows hosts?

**Comment by jborean93** [comment]
So the format of the value has not changed with that PR but rather the timezone the value represents has. If you were having issues trying to filter it with `strftime` then you will continue to have issues after that change.

**Comment by xenlo** [comment]
Indeed. I misunderstood the original bug report. Sorry for that.

Never the less, I created an issue about `strftime`not dealing with float numbers here: https://github.com/ansible/ansible/issues/71257.

In the meantime, I apply the following split filter as workaround: 
```
{{ '%b %d %Y %H:%M:%S %Z' | strftime(ansible_date_time.epoch.split('.')[0]) }}
```

**Comment by jborean93** [comment]
If the epoch contains milliseconds then you should need to adjust your date format to include that. I belive in Python thats `%f` so your date format would be

```
{{ '%b %d %Y %H:%M:%S.%f %Z' | strftime(ansible_date_time.epoch) }}
```

**Comment by xenlo** [comment]
I also found the reference of `%f` in the [python strftime doc](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes). I didn't added it because I need that precision in my template.
