### ISSUE TITLE
win_service failed with access denied

### ISSUE THREAD

**Issue by derhoeppi** [ansible-collections/ansible.windows#269]
##### SUMMARY
If i'm running a role with a task win_service then it will fail with "Access denied". This problems occurs on Windows Server 2019, Windows Server 2022 and Windows 10 21H1. This failure does not exists on Windows Server 2016 and older Windows 10 versions. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.windows --> task: win_service

##### ANSIBLE VERSION

```
ansible [core 2.12.0.dev0]
  config file = None
  configured module search path = [&apos;/home/runner/.ansible/plugins/modules&apos;, &apos;/usr/share/ansible/plugins/modules&apos;]
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
```
Same Problem with ansible 2.11.4.

##### COLLECTION VERSION

```
# /usr/share/ansible/collections/ansible_collections
Collection                     Version
------------------------------ -------
amazon.aws                     1.5.0  
ansible.netcommon              2.3.0  
ansible.posix                  1.3.0  
ansible.utils                  2.3.1  
ansible.windows                1.7.2  
.
.
.
community.vmware               1.13.0 
community.windows              1.6.0  
community.zabbix               1.4.0 
.
.
.

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Target systems are Windows Server 2019, Windows Server 2022 and the latest version of Windows 10

##### STEPS TO REPRODUCE

1. Write a new role or playbook with an win_service task
2. Run this against the target systems

```
 - win_service:
    name: mpssvc

```

##### EXPECTED RESULTS

I want to retriev a return value if the service is running or not.

##### ACTUAL RESULTS

```
{
  "exception": "Exception calling \".ctor\" with \"2\" argument(s): \"Failed to open service 'mpssvc' (Access is denied, Win32ErrorCode 5 - 0x00000005)\"\r\nAt line:919 char:5\r\n+     New-Object -TypeName Ansible.Windows.SCManager.Service -ArgumentL ...\r\n+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException\r\n    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 919\r\nat Get-ServiceFromName, <No file>: line 274\r\nat <ScriptBlock>, <No file>: line 918\r\n\r\nSystem.Management.Automation.MethodInvocationException: Exception calling \".ctor\" with \"2\" argument(s): \"Failed to open service 'mpssvc' (Access is denied, Win32ErrorCode 5 - 0x00000005)\" ---> ansible_collections.ansible.windows.plugins.module_utils.SCManager.ServiceManagerException: Failed to open service 'mpssvc' (Access is denied, Win32ErrorCode 5 - 0x00000005)\r\n   at ansible_collections.ansible.windows.plugins.module_utils.SCManager.Service..ctor(String name, ServiceRights access, SCMRights scmAccess) in c:\\Users\\User1\\AppData\\Local\\Temp\\zx132r4y.0.cs:line 1178\r\n   --- End of inner exception stack trace ---\r\n   at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation, Object[] arguments, Object[] originalArguments)\r\n   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors, Object[] arguments)\r\n   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors, Object[] args)",
  "msg": "Unhandled exception while executing module: Exception calling \".ctor\" with \"2\" argument(s): \"Failed to open service 'mpssvc' (Access is denied, Win32ErrorCode 5 - 0x00000005)\"",
  "_ansible_no_log": false,
  "changed": false
}

```

**Comment by jborean93** [comment]
If all you are wanting to do is to get the status of a service you could try out `win_service_info` instead as that will most likely only open the service with read access rather than some of the modify rights.

If the system is returning access is denied then there's not much else that can be done. The module is trying to open it with more rights than what it has access to. I personally cannot find any reason why that would be the case on my server 2019 host but potentially it has been changed. You can run the following to get some more information in the DACL of a service.

```powershell
(ConvertFrom-SddlString ((sc.exe sdshow mpssvc) -join '').Trim()).DiscretionaryAcl
```

Based on your module options, the module will be trying to open the service handle with the access mask `QueryConfig`, `QueryStatus`, `EnumerateDependents`, `ChangeConfig`. Whereas `win_service_info` doesn't require the `ChangeConfig` access making it usuable in more restrictive scenarios.

**Comment by derhoeppi** [comment]
I tested win_service_info and it works as designed - but i have to use the whole FQCN (ansible.windows.win_service_info) -> the short win_service_info is not possible.
When i try to get 
`(ConvertFrom-SddlString ((sc.exe sdshow mpssvc) -join '').Trim()).DiscretionaryAcl` from server 2016, 2019 and 2022 - i get some differences.  The return values doest not include QueryConfig, QueryStatus, EnumerateDependents or ChangeConfig. Where i can see this one?

**Comment by jborean93** [comment]
>  but i have to use the whole FQCN (ansible.windows.win_service_info) -> the short win_service_info is not possible.

Yep, all modules added to this collection that did not exist before in Ansible need to be referenced by the FQCN. You could add `collections: ['ansible.windows']` to the play to add it to the search path so you don't need the FQCN as well.

> The return values doest not include QueryConfig, QueryStatus, EnumerateDependents or ChangeConfig. 

The names I gave you are ones used by the code internally and `ConvertFrom-SddlString` uses generic values to represent the access mask. Running this script will give you a better representation of the rights uses

```powershell
# https://docs.microsoft.com/en-us/windows/win32/services/service-security-and-access-rights
Add-Type -TypeDefinition @'
using System;

namespace SCManager
{
    [Flags]
    public enum AccessMask
    {
        QueryConfig = 0x00000001,
        ChangeConfig = 0x00000002,
        QueryStatus = 0x00000004,
        EnumerateDependents = 0x00000008,
        Start = 0x00000010,
        Stop = 0x00000020,
        PauseContinue = 0x00000040,
        Interrogate = 0x00000080,
        UserDefinedControl = 0x00000100,
        Delete = 0x00010000,
        ReadControl = 0x00020000,
        WriteDac = 0x00040000,
        WriteOwner = 0x00080000,
        AllAccess = 0x000F01FF,
        AccessSystemSecurity = 0x01000000,
    }
}
'@

$sddl = ((sc.exe sdshow mpssvc) -join "").Trim()
$sd = ConvertFrom-SddlString -Sddl $sddl
$sd.RawDescriptor.DiscretionaryAcl | ForEach-Object {
    $sid = $_.SecurityIdentifier
    try {
        $account = $sid.Translate([Security.Principal.NTAccount])
    } catch [Security.Principal.IdentityNotMappedException] {
        $account = $sid
    }
    [PSCustomObject]@{
        Account = $account
        Access = [SCManager.AccessMask]$_.AccessMask
        AccessMask = '0x{0:X8}' -f $_.AccessMask
        AceType = $_.AceType
    }
} | Format-List
```

**Comment by derhoeppi** [comment]
Today i can run your snippet to get the correct return values. My ansible_user is in the local administrator group. I could not find any changes between server 2019 and 2022 but server 2016 is different. Here are the results.
server 2016:
`Account    : NT AUTHORITY\INTERACTIVE
Access     : QueryConfig, QueryStatus, EnumerateDependents, Interrogate, UserDefinedControl, ReadControl
AccessMask : 0x0002018D
AceType    : AccessAllowed

Account    : NT AUTHORITY\SERVICE
Access     : QueryConfig, QueryStatus, EnumerateDependents, Interrogate, UserDefinedControl, ReadControl
AccessMask : 0x0002018D
AceType    : AccessAllowed

Account    : NT AUTHORITY\SYSTEM
Access     : QueryConfig, QueryStatus, EnumerateDependents, Start, Stop, PauseContinue, Interrogate,
             UserDefinedControl, ReadControl
AccessMask : 0x000201FD
AceType    : AccessAllowed

Account    : BUILTIN\Administrators
Access     : AllAccess
AccessMask : 0x000F01FF
AceType    : AccessAllowed`

server 2019 / 2022:
`Account    : NT AUTHORITY\Authenticated Users
Access     : QueryConfig, QueryStatus, Interrogate, ReadControl
AccessMask : 0x00020085
AceType    : AccessAllowed

Account    : NT AUTHORITY\SYSTEM
Access     : QueryConfig, ChangeConfig, QueryStatus, EnumerateDependents, Start, Interrogate, ReadControl, WriteDac, WriteOwner
AccessMask : 0x000E009F
AceType    : AccessAllowed

Account    : BUILTIN\Administrators
Access     : QueryConfig, QueryStatus, EnumerateDependents, Start, Interrogate, ReadControl, WriteDac, WriteOwner
AccessMask : 0x000E009D
AceType    : AccessAllowed

Account    : BUILTIN\Users
Access     : QueryConfig, QueryStatus, Interrogate
AccessMask : 0x00000085
AceType    : AccessAllowed`

It look likes the server 2016 administrators has no restrictions (AllAccess). Could you verify this problem on your server 2019?

**Comment by jborean93** [comment]
I can verify that server 2016 has `AllAccess` and 2019 has `QueryConfig, QueryStatus, EnumerateDependents, Start, Interrogate, ReadControl, WriteDac, WriteOwner`. Unfortunately this means that the `ChangeConfig` right is not allowed for `Administrators` by default and thus the access denied error is as expected. There's not much that can be done about this and the workaround is to use `win_service_info` to get the service information. You can always edit the DACL of this particular service to grants the rights to `Administrators` but there would be a reason that MS has restricted what is allowed by default.
