### ISSUE TITLE
typo in git tag for version 1.7.2?

### ISSUE THREAD

**Issue by shk3bq4d** [ansible-collections/ansible.windows#270]
Hello,

previous version tags had a v in the git tag name such as in

* v1.6.0
* v1.7.0
* v1.7.1

tag for release 1.7.2 has no "v".

I assume this is not intended.

Best regards,

**Comment by jborean93** [comment]
Unfortunately the release process that this collection (and soon to be `community.windows`) expects the tag to be without the `v` so any future releases will just be `x.y.z`.
