### ISSUE TITLE
_reboot.py returns "local variable 'e' referenced before assignment" instead of friendly error

### ISSUE THREAD

**Issue by helveciofneto** [ansible-collections/ansible.windows#276]
##### SUMMARY

_reboot.py returns "local variable 'e' referenced before assignment" instead of friendly error when using "become: true" with ansible.windows.win_reboot

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.windows.win_reboot

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.3] 
  config file = None
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/vagrant/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/vagrant/.local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection      Version
--------------- -------
ansible.windows 1.7.0 
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Reboot
  ansible.windows.win_reboot:
    reboot_timeout: 120
    post_reboot_delay: 180
  become: true
```

##### EXPECTED RESULTS

Friendly error message regarding the use of "become" with Windows modules or something similar.

##### ACTUAL RESULTS

On line 340 looks like there is a `raise e` outside of the try/except loop where it is declared. When hit, this line causes the reference error.

```paste below
Traceback (most recent call last):
  File \"/tmp/awx_212044_jhdqqdej/requirements_collections/ansible_collections/ansible/windows/plugins/plugin_utils/_reboot.py\", line 148, in reboot_host
    task_action, connection, boot_time_command)
  File \"/tmp/awx_212044_jhdqqdej/requirements_collections/ansible_collections/ansible/windows/plugins/plugin_utils/_reboot.py\", line 273, in _do_until_success_or_retry_limit
    func, *args, **kwargs)
  File \"/tmp/awx_212044_jhdqqdej/requirements_collections/ansible_collections/ansible/windows/plugins/plugin_utils/_reboot.py\", line 340, in _do_until_success_or_condition
    raise e
UnboundLocalError: local variable 'e' referenced before assignment

```

**Comment by helveciofneto** [comment]
I couldn't consistenly reproduce the issue... sometimes everything works, sometimes I get this error. I'm no longer sure it's related to the `become` directive, but anyway, I still question this `raise e` outside the block it's referenced in.

**Comment by jborean93** [comment]
This particular issue should be fixed with https://github.com/ansible-collections/ansible.windows/pull/277 (thanks for the PR). The actual cause of the connection issue could be anything really. This part of the code is designed to handle connection failures when trying to run commands as the host is rebooting. Hopefully with the variable reference before assignment fix you can now get a better indication of what might be going wrong.

**Comment by helveciofneto** [comment]
Thanks! indeed I narrowed down my case to the user in `ansible_user` no longer being available by the time the reboot command was attempted, which caused a 401 error in the PSRP connection, and then triggered this other exception. Definetly this fix will get it covered.
