### ISSUE TITLE
No 'Split' method Exception from win_dns_client.ps1

### ISSUE THREAD

**Issue by frisch-raphael** [ansible-collections/ansible.windows#283]
##### SUMMARY

To be fair it seems I'm missing something obvious, but after trying to solve it for a few days I figured I'd ask help.
When trying to use ansible.windows.win_dns_client, the win_dns_client.ps1 script thrown the following exception:

```
Method invocation failed because [System.Byte] does not contain a method named 'Split'.
At line:138 char:43
```

I tried the script directly inside the target VM and wasn't able to reproduce the exception.
The problem seems to be that, at this part of win_dns_client.ps1
```
                if (($ns = Get-OptionalProperty -InputObject $iprop -Name $items.DhcpNameServer)) {
                    $famInfo.EffectiveNameServers = $famInfo.DhcpAssignedNameServers = $ns.Split(' ')
                }
```
$ns is not a string for some reason, but a byte array instead.
The target VM is on VMWare workstation and has both a NAT and a bridged interface.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Issue seems to come from win_dns_client.ps1 used by win_dns_client.

##### ANSIBLE VERSION

```
ansible 2.10.8
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Sep  3 2021, 06:18:44) [GCC 10.3.0]
```

##### COLLECTION VERSION

After trying with the default ansible.windows 1.4.0, I tried to install the most recent one with 

```ansible-galaxy collection install ansible.windows```

which installed the version 1.7.3
```
ansible-galaxy collection list ansible.windows 

# /root/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
ansible.windows 1.7.3 
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
(no output)                                                                                                
```

##### OS / ENVIRONMENT

Got the same error for both those Vagrant boxes :
- StefanScherer/windows_2019
- StefanScherer/windows_10
Ansible is installed on the latest release of Kali Linux

##### STEPS TO REPRODUCE

Here are the minimal steps:
Create the following host file (host)

```
[win_workstation]
192.168.1.102

[win_workstation:vars]
ansible_user=vagrant
ansible_password=vagrant
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
```

And this task (win_workstation_test.yml)
```
- name: ethicalhackers.fr workstation configuration
  hosts: win_workstation
  tasks:

  - name: Configure dns
    win_dns_client:
      adapter_names: '*'
      # Also tried with the name instead of a wildcard
      ipv4_addresses:
      - 192.168.1.100
      # Also tried with empty ipv4_addresses

```
Then use the command:

`ansible-playbook -i hosts win_workstation_test.yml `

##### EXPECTED RESULTS

Expected the task to return OK, and a DNS server to be configured.

##### ACTUAL RESULTS

```
ansible-playbook -i hosts_test win_workstation_test.yml -vvv
ansible-playbook 2.10.8
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.7 (default, Sep  3 2021, 06:18:44) [GCC 10.3.0]
No config file found; using defaults
host_list declined parsing /mnt/hgfs/AD-lab/hosts_test as it did not pass its verify_file() method
auto declined parsing /mnt/hgfs/AD-lab/hosts_test as it did not pass its verify_file() method
Parsed /mnt/hgfs/AD-lab/hosts_test inventory source with ini plugin
redirecting (type: modules) ansible.builtin.win_dns_client to ansible.windows.win_dns_client
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: win_workstation_test.yml **********************************************************************************
1 plays in win_workstation_test.yml

PLAY [ethicalhackers.fr workstation configuration] ******************************************************************

TASK [Gathering Facts] **********************************************************************************************
task path: /mnt/hgfs/AD-lab/win_workstation_test.yml:3
redirecting (type: modules) ansible.builtin.setup to ansible.windows.setup
Using module file /root/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/setup.ps1
Pipelining is enabled.
<192.168.1.102> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5986 TO 192.168.1.102
EXEC (via pipeline wrapper)
ok: [192.168.1.102]
META: ran handlers

TASK [Configure dns] ************************************************************************************************
task path: /mnt/hgfs/AD-lab/win_workstation_test.yml:7
redirecting (type: modules) ansible.builtin.win_dns_client to ansible.windows.win_dns_client
Using module file /root/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_dns_client.ps1
Pipelining is enabled.
<192.168.1.102> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5986 TO 192.168.1.102
EXEC (via pipeline wrapper)
The full traceback is:
Method invocation failed because [System.Byte] does not contain a method named 'Split'.
At line:138 char:43
+             $reg_info = $adapter_config | Get-RegistryNameServerInfo
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-RegistryNameServerInfo], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound,Get-RegistryNameServerInfo

ScriptStackTrace:
at Get-RegistryNameServerInfo<Process>, <No file>: line 198
at <ScriptBlock>, <No file>: line 138
at Get-NetAdapterInfo<Process>, <No file>: line 122
at <ScriptBlock>, <No file>: line 325

System.Management.Automation.RuntimeException: Method invocation failed because [System.Byte] does not contain a method named 'Split'.                                                                                                    
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)                                                                                                           
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)                                                                                                                
   at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
fatal: [192.168.1.102]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Method invocation failed because [System.Byte] does not contain a method named 'Split'."                                                                                          
}
```

**Comment by jborean93** [comment]
The issue here is that it's trying to get the registry property `DhcpNameServer` under `HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{interface guid}` and it's expecting that property to be a `REG_SZ` (string). Because the property is present but not a string it's failing to get the information it expects. Can you check all the interfaces under `HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces` to see if the property `DhcpNameServer` or `Dhcpv6DNSServers` is present and what types/values they are set to?

**Comment by frisch-raphael** [comment]
Hi jborean93,

You're absolutly right. One of the Dhcpv6DNSServers property from HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters\Interfaces\ was set on "reg_binary".

![2021-09-27_195450](https://user-images.githubusercontent.com/3451172/134960490-b0e9b15a-81ee-44b2-89ac-26c3c867c384.png)

After deleting this interface the task is proceeding as expected.

```
└─# ansible-playbook -i hosts win_workstation.yml --tags "dns"                                                                                                                                                                           2 ⨯

PLAY [ethicalhackers.fr workstation configuration] ******************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [192.168.1.102]

TASK [Configure dns] ************************************************************************************************************************************************************************************************************************
changed: [192.168.1.102]

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
192.168.1.102   
```

Do you think this case comes from my setup ? If not, I can try to make a pull request to win_dns_client.ps1 to manages this particular case.

**Comment by jborean93** [comment]
That would definitely cause the problem. The value is representing an IPv6 address `fe80:0000:0000:0000:f282:61ff:fee9:f738` but instead of it being represented by a string it's represented with raw binary values. I've spoken with the author of this code https://github.com/ansible/ansible/pull/66451 and it looks like this was mostly undefined behaviour as they didn't have access to an IPv6 enabled network. I've since set up an environment with IPv6 and I can replicate what you are seeing. Unfortunately there are no docs from MS to confirm this behaviour but we can definitely handle it in the code based on what we can see.

To convert this value to an IPv6 string we could do something like:

```powershell
if (($ns = Get-OptionalProperty -InputObject $iprop -Name $items.DhcpNameServer)) {
    if ($ns -is [byte[]]) {
        # Is an IPv6 address, IPAddress is able to easily parse this and produce the string value.
        $ns = (New-Object -TypeName System.Net.IPAddress -ArgumentList @(,$ns)).IPAddressToString
    }

    $famInfo.EffectiveNameServers = $famInfo.DhcpAssignedNameServers = $ns.Split(' ')
}
```

The one thing I'm unsure of is how multiple servers are encoded in this field. I cannot produce an environment that has the DHCPv6 provide multiple addresses so this example will only work when 1 is set. The `StaticNameServer` code below should continue to work as my IPv6 address has that set to a string value anyway just like IPv6.

![image](https://user-images.githubusercontent.com/8462645/134983180-dd29cc54-3eb5-4c8e-bd32-ee24174d0466.png)

> Do you think this case comes from my setup ? If not, I can try to make a pull request to win_dns_client.ps1 to manages this particular case.

If you feel up to making a pull request that will be great. It definitely seems like something we need to handle. It would be great if we could test this in CI but I don't think that's going to be feasible as the network interface that's created specifically for the test won't have IPv6 configured.

**Comment by jborean93** [comment]
I've spoken with someone who has multiple addresses set by DHCP and it looks like it's not delimited with any value and just appends the bytes. Because it's a fixed length value we could adjust the check to become:

```powershell
if (($ns = Get-OptionalProperty -InputObject $iprop -Name $items.DhcpNameServer)) {
    # BinaryLength would have to be added to the $protoItems entry - 4 for IPv4 and 16 for IPv6
    $famInfo.EffectiveNameServers = $famInfo.DhcpAssignedNameServers = @(if ($ns -is [byte[]]) {
        for ($i = 0; $i -lt $ns.Length; $i += $items.BinaryLength) {
            [byte[]]$ipBytes = $ns[$i..($i + $items.BinaryLength - 1)]
            (New-Object -TypeName System.Net.IPAddress -ArgumentList @(,$ipBytes)).IPAddressToString
        }
    } else {
        $ns.Split(' ')
    })
}
```

The only extra addition is to add `BinaryLength` to the IPv4 and IPv6 `$protoItems` metadata so the code knows how long the byte length is for the address type.

**Comment by frisch-raphael** [comment]
Thanks for the code snippet @jborean93, and for your effectiveness in resolving this issue.
After modifying win_dns_client.ps1 as per your advices, I was able to change the DNS server through ansible. I'll make a pull request with the code I used.

Also, while it is not related to this issue, and I don't know if this behavior is wanted, but the object returned by _Get-RegistryNameServerInfo_ contains duplicated properties from both IPv4 and IPv6 configurations.

![image](https://user-images.githubusercontent.com/3451172/135075211-9865e9a7-4eaa-4925-99e5-5ba25590b2a5.png)

This seemed weird to me but with my very limited knowledge on how the base code works I didn't investigate any further.

**Comment by briantist** [comment]
> Also, while it is not related to this issue, and I don't know if this behavior is wanted, but the object returned by _Get-RegistryNameServerInfo_ contains duplicated properties from both IPv4 and IPv6 configurations.
> 
> ![image](https://user-images.githubusercontent.com/3451172/135075211-9865e9a7-4eaa-4925-99e5-5ba25590b2a5.png)
> 
> This seemed weird to me but with my very limited knowledge on how the base code works I didn't investigate any further.

This last part is because it's returning an object _per_ address family. It's just showing up on screen all mashed together.

If you run ` Get-RegistryNameServerInfo | measure` you should see a count of 2. 
Or `nsi =  Get-RegistryNameServerInfo ; $nsi.Count ; echo $nsi[0] '------' $nsi[1]`.
