### ISSUE TITLE
Windows 2022 support

### ISSUE THREAD

**Issue by sugitk** [ansible-collections/ansible.windows#322]
##### SUMMARY

Windows 2022 is not included in the list at the host requirements, do we have a plan to support it?

https://docs.ansible.com/ansible/latest/user_guide/windows_setup.html#host-requirements

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by jborean93** [comment]
I've just opened https://github.com/ansible/ansible/pull/76582 which mentions 2022 in the Ansible docs. We test against 2022 in both this collection and Ansible core so I'm happy to say things work just fine and is supported on the community side. As for support from Red Hat this needs to come from the Support BU (or product team) and would need to be asked internally. If it is then it's up to them to update the Red Hat documentation to mention this.

**Comment by jborean93** [comment]
There's nothing left that can be done in this repo for this. It's being worked on internally to update documentation to cover this particular point.
