### ISSUE TITLE
win_reboot no explicit confirmation if there's equivalence with `shutdown /f`

### ISSUE THREAD

**Issue by AbianG** [ansible-collections/ansible.windows#336]
##### SUMMARY

Currently, the [documentation](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_reboot_module.html) for the win_reboot module has no explicit way to know if its equivalent of running `shutdown /r /f`, that is, forcing the remote host to reboot. Older [versions (2.6)](https://docs.ansible.com/ansible/2.6/modules/win_reboot_module.html) show an example defined as "Unconditionally reboot the host", so it can be inferred, but explicit is always preferred. I think this could be a good improvement for the documentation of the module, but before editing it I would like confirmation.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

win_reboot

##### ANSIBLE VERSION

```paste below

```

**Comment by jborean93** [comment]
The plugin uses `shutdown /r /t x` as per https://github.com/ansible-collections/ansible.windows/blob/928f16304fb1ea22cbd3e784ed23b03423e556ad/plugins/plugin_utils/_reboot.py#L185. I can't guarantee this will be the same in the future but we've used this set of arguments for a while.

**Comment by AbianG** [comment]
Thank you for the quick response. As by default the module sends 2 seconds as the pre-reboot delay, that shutdown will behave as a `/f` (per [MS documentation](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/shutdown), if `/t` is greater than 0 `/f` is implied). 

If I'm correct, I think the module's documentation would benefit of stating this: If pre_reboot_delay is higher than 0 (by default its 2) the command will imply a forced (/f) reboot.

**Comment by jborean93** [comment]
I'm more than happy to accept a PR with the changes you think it should have. The changes would need to be made to https://github.com/ansible-collections/ansible.windows/blob/main/plugins/modules/win_reboot.py and the docs under `docs` are updated on the next release from this file.

Just as an FYI the value of 2 is now a minimum, it cannot be less than that value as it causes problems when trying to reboot the host.

**Comment by AbianG** [comment]
Thanks for the quick response and clear information!  That 2 minimum value definitely makes this module behave like `/f`.
I'll work on the PR.

**Comment by AbianG** [comment]
Sorry @jborean93, but I am unable to push a PR to the ansible.windows repository, I get a permission error when trying to push the changes in my own branch either by HTTPS or SSH
