### ISSUE TITLE
win_path and win_environment should support messaging trigger to WM_SETTINGCHANGE

### ISSUE THREAD

**Issue by gillg** [ansible-collections/ansible.windows#348]
According to https://docs.microsoft.com/en-us/windows/win32/procthread/environment-variables and https://www.angryadmin.co.uk/?p=855, using powershell to set env vars is effective in the registry but all running processes will not be affected.
That makes sense usualy but it could be super convinient to trigger WM_SETTINGCHANGE to refresh the services stack (where the process parent is svchost.exe) or ansible connection itself in case of agent like AWS SSM Agent or any transport layer provided by a third party.

The idea is to let windows refresh processes env when ansible change a value, like if you did it on the UI.

**Comment by jborean93** [comment]
This sounds like a decent idea to implement and shouldn't be too hard to add. Will try and add this for the next release.

**Comment by jborean93** [comment]
https://github.com/ansible-collections/ansible.windows/pull/352 contains the changes, if you get a chance it would be great if you could test it out.

**Comment by gillg** [comment]
Great! Thank you @jborean93 , I will try to take some time to test it. Maybe not this week, but I will try !
