### ISSUE TITLE
win_updates - return value "updates" dictionary parsing suggestion

### ISSUE THREAD

**Issue by iamperson347** [ansible-collections/ansible.windows#351]
##### SUMMARY

win_updates's return value includes an "updates" dictionary whose key for each item is a guid. This appears to create an issue while looping through results. I believe this is due to dashes not being allowed in attribute names. I think guid makes sense to have as the key for the dictionary, but maybe it would be helpful to have an example in the documentation on how to parse results (if looping)? dict2items worked well for me to fix the issue I was seeing. 

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
win_updates

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.3]

```

**Comment by agibson2** [comment]
This is how I show updates as the last task after they were installed...

`  For the update, register update_result of course like the line below.  I also change the name of the task depending on if it is applying the update or just checking in --check mode.
    - name: "{{ 'Check' if ansible_check_mode else 'Apply' }} updates"
      register: update_result

    - name: Show updates
      vars:
        msg: |
            {% for k in update_result.updates %}
            {{ 'Needed' if ansible_check_mode else 'Installed' }}: {{ update_result.updates[k].title }}
            {% endfor %}
            {% for kk in update_result.filtered_updates %}
            Filtered: {{ update_result.filtered_updates[kk].title }} ({{ update_result.filtered_updates[kk].filtered_rea
son }})
            {% endfor %}
      debug:
        msg: "{{ msg.split('\n')[:-1] }}"`

**Comment by jborean93** [comment]
This is a question best left for the Ansible mailing list of IRC which can be found at

   * IRC: #ansible or #ansible-windows on [irc.libera.chat](https://libera.chat/)
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

We try to keep this issue tracker for bug reports and direct user questions to IRC or the mailing list.
