### ISSUE TITLE
win_package getting error - Get-AnsibleWindowsWebRequestSpec not found

### ISSUE THREAD

**Issue by sabman3** [ansible-collections/ansible.windows#358]
##### SUMMARY
Using Ansible 2.9.27 (Red Hat). Switched task to use FQCN (ansible.windows.win_package) for module and now getting error.  I believe the underlying issue is that it does not reconize all the functions from module_utlils/WebRequest.psm1. However I'm not a PowerShell expert.

 "Unhandled exception while executing module: The term 'Get-AnsibleWindowsWebRequestSpec' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_package

##### ANSIBLE VERSION
```
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]


```

##### COLLECTION VERSION

```
1.10.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```
# Uninstall Older Opnet if exists
- name: Uninstall Older Opnet
ansible.windows.win_package:
path: C:\Program Files (x86)\InstallShield Installation Information\{132F7D38-FA45-11D5-BDC3-00104B938A09}\setup.exe
product_id: '{132F7D38-FA45-11D5-BDC3-00104B938A09}'
arguments: /s /f1c:\temp\AppCaptureCurrent\opnet-uninstall.iss
state: absent
```

##### EXPECTED RESULTS
packaged uninstalled

##### ACTUAL RESULTS

```paste below

```

**Comment by jborean93** [comment]
This collection is only set to work with Ansible 2.10 and you are on Ansible 2.9. You will need to update your Ansible version or stick with `win_package` that comes with Ansible 2.9.

**Comment by sabman3** [comment]
Thanks for the quick response. But Red Hat only support 2.9. So I guess I'm stuck. Unless you are aware of something else.

**Comment by jborean93** [comment]
Red Hat supports beyond 2.9, you should talk to your service rep about this.
