### ISSUE TITLE
win_updates fails with "SuceededWithErrors 3" 

### ISSUE THREAD

**Issue by anasaizg** [ansible-collections/ansible.windows#366]
##### SUMMARY

In some servers, win_updates fails with the following message: "Failed to search for updates (SuceededWithErrors 3)". However, when update is launched manually, there seems to be no errors.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_updates

##### ANSIBLE VERSION

```
ansible 2.10.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/my-envs/venv-windows/lib64/python3.6/site-packages/ansible
  executable location = /opt/my-envs/venv-windows/bin/ansible
  python version = 3.6.8 (default, Nov 18 2021, 10:07:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

```

##### COLLECTION VERSION

```
Collection      Version
--------------- -------
ansible.windows 1.9.0

```

##### OS / ENVIRONMENT

Target OS: Microsoft Windows Server 2016 Standard
Powershell version: 5
Connection Type: PSRP

##### STEPS TO REPRODUCE

```
- name: Windows updates - log to {{ansible_log}}
  ansible.windows.win_updates:
    category_names: "{{ category_updates |default('*') }}"
    state: installed
    log_path: "{{ ansible_log }}"
    reboot: yes
    reboot_timeout: 3600
  register: win_updates_result
  ignore_errors: yes

- debug:
    var: win_updates_result
```

##### EXPECTED RESULTS
Server is updated after some minutes (or hours, depending on the patches)

##### ACTUAL RESULTS
Update task fails and the following data is registered:

```
{
    "win_updates_result": {
        "changed": true,
        "reboot_required": false,
        "failed": true,
        "msg": "Failed to search for updates (SuceededWithErrors 3)",
        "exception": "Failed to search for updates (SuceededWithErrors 3)\r
At line:757 char:9\r
+         throw \"Failed to search for updates ($resCode $([int]$resCode ...\r
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r
    + CategoryInfo          : OperationStopped: (Failed to searc...edWithErrors 3):String) [], RuntimeException\r
    + FullyQualifiedErrorId : Failed to search for updates (SuceededWithErrors 3)\r
 \r
\r
\r
at <ScriptBlock>, <No file>: line 757",
        "found_update_count": 0,
        "failed_update_count": 0,
        "installed_update_count": 0,
        "updates": {},
        "filtered_updates": {}
    },
    "_ansible_verbose_always": true,
    "_ansible_no_log": false,
    "changed": false
}

```

I have checked the log in the server but the same info is given, e.g.:

```
2022-05-30 23:30:56Z Reboot requirement check: False
2022-05-30 23:30:56Z Creating Windows Update session...
2022-05-30 23:30:56Z Create Windows Update searcher...
2022-05-30 23:30:56Z Setting the Windows Update Agent source catalog...
2022-05-30 23:30:56Z Search source set to 'default' (ServerSelection = 0)
2022-05-30 23:30:56Z Searching for updates to install with query 'IsInstalled = 0'
2022-05-30 23:31:30Z Exception encountered:
{
    "action":  null,
    "exception":  {
                      "message":  "Failed to search for updates (SuceededWithErrors 3)",
                      "exception":  "Failed to search for updates (SuceededWithErrors 3)\r
At line:757 char:9\r
+         throw \"Failed to search for updates ($resCode $([int]$resCode ...\r
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r
    + CategoryInfo          : OperationStopped: (Failed to searc...edWithErrors 3):String) [], RuntimeException\r
    + FullyQualifiedErrorId : Failed to search for updates (SuceededWithErrors 3)\r
 \r
\r
\r
at \u003cScriptBlock\u003e, \u003cNo file\u003e: line 757"
                  },
    "reboot_required":  false,
    "failed":  true,
    "changed":  false
}
Exiting...
```

We get the same results if we try launching the update after a reboot. However, if the update is done manually in the server, it doesn't complain about any errors. No further information on the error is given.

This happens with several servers whereas others with the same configuration (apparently) update smoothly.

I can try and get more information if needed.

Thanks!

**Comment by jborean93** [comment]
Unfortunately it doesn't look like the module writes any information as to why the update may have failed with errors. We can probably change the behaviour to just display a warning if the search had `SuceededWithErrors` but I would be reluctant to do that for the download and install phase. The trouble is trying to get any further info as to what those errors actually were. I see the [ISearchResult](https://docs.microsoft.com/en-us/windows/win32/api/wuapi/nn-wuapi-isearchresult) value contains a `Warnings` property which is a collection of exceptions but without actually replicating this scenario I'm not sure if I can write code that will correctly extract the warning information from that. COM makes this a lot more difficult to do.

Could you try running the following on a server that returns the `SuceededWithErrors` value and see if this gives you back any more information?

```yaml
- ansible.windows.win_powershell:
    script: |
      $session = New-Object -ComObject Microsoft.Update.Session
      $searcher = $session.CreateUpdateSearcher()
      $res = $searcher.Search('IsInstalled = 0')

      [PSCustomObject]@{
          ResultCode = $res.ResultCode
          WarningCount = $res.Warnings.Count
          Warnings = @(
              for ($i = 0; $i -lt $res.Warnings.Count; $i++) {
                  $warning = $res.Warnings.Item($i)
                  [PSCustomObject]@{
                      Message = $warning.Message
                      HResult = $warning.HResult
                      Context = $warning.Context
                  }
              }
          )
      }
  become: yes
  become_method: runas
  vars:
    ansible_become_user: '{{ ansible_user }}'
    ansible_become_pass: '{{ ansible_password }}'
```

Based on the docs this should hopefully return the warning information (if present). If not it will at least confirm that if the result code was `3` whether there are warnings we can display. Please note become needs to be used here and the example above should just be running as the same user as the one that's connecting to the host.

**Comment by jborean93** [comment]
The PR https://github.com/ansible-collections/ansible.windows/pull/372 contains the above code and should output any warning info (if the code I shared above actually works) to the log file. If you do find this failure you should be able to see the error information in there and determine what to do next.

**Comment by anasaizg** [comment]
Thanks for the fast reply @jborean93, I'll try to run this task and see what we get
