### ISSUE TITLE
win_domain_membership: Rename not working

### ISSUE THREAD

**Issue by brian-lamb-software-engineer** [ansible-collections/ansible.windows#376]
Issue already reported [here](https://github.com/ansible-collections/ansible.windows/issues/19), still happening. I was sad to see that one was closed.  It is not odd, its an ongoing issue for v 2.9.  I cant use v3, so need to stick with 2.9.  

##### SUMMARY

The following task

```yaml
  - name: Join "{{ domain_name }}" domain
    ansible.windows.win_domain_membership:
      dns_domain_name: "{{ domain_name }}"
      hostname: "some_prefix{{ hostvars[inventory_hostname].inventory_hostname.split('.') | last }}"
      domain_admin_user: "{{ domain_user }}"
      domain_admin_password: "{{ domain_password }}"
      state: domain
    register: res_domain_return
```

Causes this error:

```
changed: [10.124.10.17]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 274
fatal: [10.124.10.19]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Fail to rename computer 'EC2AMAZ-CCSF62Q' to 'some_prefix19' due to the following exception: The specified computer account could not be found. Contact an administrator to verify the account is in the domain. If the account has been deleted unjoin, reboot, and rejoin the domain."}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_domain_membership

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /home/<myuser>/src/labos/ansible/ansible.cfg
  configured module search path = ['/home/<myuser>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
```

##### COLLECTION VERSION
```
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')
```

##### CONFIGURATION
```
DEFAULT_LOG_PATH(/home/<myuser>/src/labos/ansible/ansible.cfg) = /home/<myuser>/src/labos/ansible/ansible.log
HOST_KEY_CHECKING(/home/<myuser>/src/labos/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
controller ubuntu 20.04.4 LTS
aws win 2019 server full base

##### STEPS TO REPRODUCE
Rename a system when you're joining. Potentially doing this twice with a reinstalled system using the same target name.

```yaml
  - name: Join "{{ domain_name }}" domain
    ansible.windows.win_domain_membership:
      dns_domain_name: "{{ domain_name }}"
      hostname: "some_prefix{{ hostvars[inventory_hostname].inventory_hostname.split('.') | last }}"
      domain_admin_user: "{{ domain_user }}"
      domain_admin_password: "{{ domain_password }}"
      state: domain
    register: res_domain_return
```

##### EXPECTED RESULTS
computer j\renamed then joins domain

##### ACTUAL RESULTS
computer is put into domain using default aws name, causing an erroneous entry in AD that has to be later deleted, then computer is never renamed. 

This only happens periodically, possibly when doing more than one server at a time, but not normally.  e.g. sometimes there is 2 servers that dont need the domain name change, so it skips those, and changes one only, it happens then too, randomly.  

It works most of the time.  I think its having problems connnecting to a slow responding AD at sometimes, but this too is in AWS, so should be a solid connection otherwise. 

Please have it to where it renames PC first, and then Joins!!

```
TASK [domain : Join "us.<domain>.com" domain] *****************************************************************************************************************************************************************************
changed: [10.124.10.17]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 274
fatal: [10.124.10.19]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Fail to rename computer 'EC2AMAZ-CCSF62Q' to 'some_prefix19' due to the following exception: The specified computer account could not be found. Contact an administrator to verify the account is in the domain. If the account has been deleted unjoin, reboot, and rejoin the domain."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 274
fatal: [10.124.10.51]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Fail to rename computer 'EC2AMAZ-ER7HH72' to 'some_prefix51' due to the following exception: The specified computer account could not be found. Contact an administrator to verify the account is in the domain. If the account has been deleted unjoin, reboot, and rejoin the domain."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 274
fatal: [10.124.10.20]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Fail to rename computer 'EC2AMAZ-2GFIG12' to 'some_prefix20' due to the following exception: The specified computer account could not be found. Contact an administrator to verify the account is in the domain. If the account has been deleted unjoin, reboot, and rejoin the domain."}
```

It turns out, this happens now each time i run the code, to all 4 hosts (same error message for each of the 4, as noted above). This will probably continue until i resolve the issue by renaming the hosts manally, or unjoining the domain maybe.  So it did one successfully the first run, then fails on all of them now.  thats not normal..  Ill look more into it in the morning...  

As long as I have a reboot command before it runs, it works, because it had renamed the host, and joined the domain too, but with the old name, then when ran again, it tries tries to join the domain again, and rename, but it fails to rename i think, because it needs a reboot for the first renaming still waiting to reboot . Hence pipeline fails!

--------------------------------

This is an issue, and almost related, but maybe very related.  I terminated 2 of 5 servers, ran it on both of them, it passed on one, and failed on the other.  Since it passed on one, that proves the code is sound, it failed on the other, which is a server ami that was renaming fine when the code was developed.  The problem here is notice it says `The account already exists`.  I realize thats a different issue. AD has this name already there.  But  I asked my network admin if i can just rejoin same hostname with a different server, he said we should be able to.  

``` 
TASK [domain : Join "us.<domain>.com" domain] *****************************************************************************************************************************************************************************
ok: [10.124.10.19]
ok: [10.124.10.17]
ok: [10.124.10.20]
fatal: [10.124.10.37]: FAILED! => {"changed": true, "msg": "failed to join domain: Computer 'EC2AMAZ-5B5CV5B' was successfully joined to the new domain 'us.<domain>.com', but renaming it to 'some_prefix37' failed with the following error message: The account already exists.", "reboot_required": false}
changed: [10.124.10.57]
```

So I think the problem here is that the `win_domain_membership` did not rename itself before joining the domain, like should have (requires reboot), so then its only trying to do the rename on this run, not the join, i suspect.  If this is true, then it seems to me that if it would have renamed first to the correct name, when it went to rejoin, it would have become the owner of hte `some_prefix37.us.<domain>.com` slot which already existed in ActiveDirectory (AD).  instead, it had registered as   `EC2AMAZ-5B5CV5B.us.<domain>.com` and tried to rename to `some_prefix37` so obviously AD will say that account already exists, becuse it was a rename operation.  

So if we can get it to rename first, successfully, before it joins the domain, that may be part of the problem.  Im not sure, but seems like it from this end.

**Comment by jborean93** [comment]
The PR https://github.com/ansible-collections/ansible.windows/pull/507 has deprecated the `win_domain` module in this collection in favour of [microsoft.ad.membership](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/membership_module.html#ansible-collections-microsoft-ad-membership-module) in the [microsoft.ad collection](https://github.com/ansible-collections/microsoft.ad). This collection contains various domain utilities in one common collection that is supported by myself and is part of Red Hat's Automation Platform supported collections.

The `microsoft.ad.membership` module was essentially a copy of `win_domain_membership` from this repository but was rewritten to better support scenarios like hostname renames during a domain join. It also supports a `reboot: true` option to automatically reboot the host within the module itself avoiding some of the common problems seen with trying to reboot after. I recommend you give this module a try as it should fix the problems reported here.

If it still has problems then opening an issue on the [microsoft.ad collection](https://github.com/ansible-collections/microsoft.ad) is recommended.
