### ISSUE TITLE
Microsoft AD - dynamic inventory plugin

### ISSUE THREAD

**Issue by termlen0** [ansible-collections/ansible.windows#380]
##### SUMMARY

Having a dynamic inventory use AD as a source of truth will be extremely helpful to automate against hosts controlled by that AD.
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Dynamic inventory plugin
##### ADDITIONAL INFORMATION

```yaml

```

**Comment by jborean93** [comment]
There are a few community contributions out there that provide this, just a brief search brings up

* https://github.com/mdhowle/ansible-galaxy-ad
* https://github.com/joshinryz/ansible_ldap_inventory

This is not something we are looking at adding to this collection, or `community.windows`, at this point in time so I recommend you have a look at those others or writing your own.
