### ISSUE TITLE
win_user clearing Credential Manager

### ISSUE THREAD

**Issue by Tom-Mirowski** [ansible-collections/ansible.windows#393]
Hi.

Ansible version is 2.9.2. Python version is 2.7.5. Host is RHEL7. Client is Windows 10. Expected result is password change. Actual result is password change but my credential manager is cleared.

I have two accounts on a Windows 10 VM I was given to test on, let's call them admin1 and user1.

I use Ansible on a Red Hat machine. I connect to Windows 10 via WinRM using password authentication on the admin1 account.

My dynamic inventory is just the one account

all:
children:
windows:
hosts:
123.45.678.900
vars:
ansible_user: admin1
ansible_password: password1
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
My playbook is simple

    hosts: windows
    vars:
    username: user1
    upassword: updatedPass1

    tasks:
        name: Change password
        win_user:
        name: "{{ username }}"
        password: "{{ upassword }}"
        ignore_unreachable: true
        I run the command like this

ansible-playbook -i inventory.yaml change_password.yaml
It works. However, in my Windows 10 instance, the credentials in my credential manager for the user1 account are then cleared.

This can be repeated by opening Windows 10. Going to the Credential Manager ( Start, Type in Credential Manager, click it). Clicking Add a Windows Credential. Type nonsense for the name, password. Save it.

I then run the playbook on the Red Hat machine. When I tab back to the Windows Machine and login, the credential is gone.

I confirmed if I log out of the Windows Machine and back in without running the playbook, the credential stays.

How do I get win_user to stop deleting the Credential Manager's items?
Issue Type

Bug Report
Component Name

win_user
Ansible Version

Ansible version is 2.9.2.

Configuration

Ansible version is 2.9.2.

OS / Environment

Host is RHEL7. Client is Windows 10.
Steps to Reproduce

On the Windows 10 client, first for the target account of the password change, create an entry in the Credential Manager.

**My dynamic inventory is just the one account**

all:
children:
windows:
hosts:
123.45.678.900
vars:
ansible_user: admin1
ansible_password: password1
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore

**My playbook is simple**

    hosts: windows
    vars:
    username: user1
    upassword: updatedPass1

    tasks:
        name: Change password
        win_user:
        name: "{{ username }}"
        password: "{{ upassword }}"
        ignore_unreachable: true

**I run the command like this**

ansible-playbook -i inventory.yaml change_password.yaml
**Expected Results**

Expected result is password change.
**Actual Results**

Actual result is password change but my credential manager is cleared.

**Comment by kurokobo** [comment]
This issue can easily be reproduced by following powershell command as ansible did in the module;

```powershell
$User = ([ADSI]"WinNT://$env:COMPUTERNAME").Children | Where-Object {$_.SchemaClassName -eq 'User' -and $_.Name -eq "ExampleUser"}
$User.SetPassword("MySuperSecurePassword123!")
```

So it's not ansible-related issue but windows-related issue. Sadly I don't believe that this can be controled by ansible in easy way 😢

**Comment by Tom-Mirowski** [comment]
> This issue can easily be reproduced by following powershell commands as ansible did in the module;
> 
> ```powershell
> $User = ([ADSI]"WinNT://$env:COMPUTERNAME").Children | Where-Object {$_.SchemaClassName -eq 'User' -and $_.Name -eq "ExampleUser"}
> $User.SetPassword("MySuperSecurePassword123!")
> ```
> 
> So it's not ansible-related issue but windows-related issue. I don't know if it is designed or depends on environment, but I don't believe that this can be controled by ansible in easy way cry

Hi,

As in, you don't believe its possible to use ansible to change a windows user password *without* full wiping the credential manager each time?

**Comment by kurokobo** [comment]
Hi, this is just my opinion, but I don't believe that.

- The `SetPassword` method that used in win_user module does not have any option to avoid wiping credentials: https://docs.microsoft.com/en-us/windows/win32/api/iads/nf-iads-iadsuser-setpassword
- Ansible does not touch credential manager to reset password at all. So the wiping is completely done on the Windows side.
- Technically, it may be possible to implement a temporary export of credentials and import it after password resets, but this would require complicated implementation and security-related considerations.

Of course, it may be that I just don't understand it well enough, or there may be a better solution.

**Comment by kurokobo** [comment]
That makes sence a lot, thanks for clarifyijng technical background 😃

**Comment by jborean93** [comment]
Closing as per the above, this is expected behaviour and trying to preserve the credential cache would require the existing password to be input which is not idempotent at all. As such this is unfortunately a feature we will not look at adding to `win_user`.
