### ISSUE TITLE
Reconsider docsite links

### ISSUE THREAD

**Issue by samccann** [ansible-collections/ansible.windows#412]
##### SUMMARY

The current readme points to the main branch's module docs.  Since this shows up on Galaxy, it means the user is sent to docs that may not reflect the version that is in galaxy.

Options for this are:
 - replace the link in the readme with https://docs.ansible.com/ansible/devel/collections/ansible/windows/index.htm (the devel docs on docs.ansible.com always reflect what is latest in galaxy).
  - use an approach similar to https://github.com/ansible-collections/community.hashi_vault/#collection-documentation where it links to multiple versions of the module docs.

Another problem - the docsite link in the galaxy.yml doesn't currently point to anything useful. It could point to the github pages or docs.ansible.com rather than the docsite directory in the repo as it does today.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

docs
##### ANSIBLE VERSION

```paste below

```

**Comment by jborean93** [comment]
Thanks, this has been implemented in https://github.com/ansible-collections/ansible.windows/pull/413.
