### ISSUE TITLE
win_updates fails because temporary file does not exist

### ISSUE THREAD

**Issue by anasaizg** [ansible-collections/ansible.windows#417]
##### SUMMARY

In some servers, win_updates fails with the following message: "Cannot find path 'C:\\Users\\TEMP.<User>\\AppData\\Local\\Temp\\ansible-tmp-*' because it does not exist.". However, when update is launched manually, there seems to be no errors.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_updates

##### ANSIBLE VERSION

```
ansible 2.10.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/my-envs/venv-windows/lib64/python3.6/site-packages/ansible
  executable location = /opt/my-envs/venv-windows/bin/ansible
  python version = 3.6.8 (default, Nov 18 2021, 10:07:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44.0.3)]

```

##### COLLECTION VERSION

```
Collection      Version
--------------- -------
ansible.windows 1.11.1

```

##### OS / ENVIRONMENT

Target OS: Microsoft Windows Server 2016 Standard
Powershell version: 5
Connection Type: PSRP

##### STEPS TO REPRODUCE

```
- name: Windows updates - log to {{ansible_log}}
  ansible.windows.win_updates:
    category_names: "{{ category_updates |default('*') }}"
    state: installed
    log_path: "{{ ansible_log }}"
    reboot: yes
    reboot_timeout: 3600
  register: win_updates_result
  ignore_errors: yes

- debug:
    var: win_updates_result
```

##### EXPECTED RESULTS
Server is updated after some minutes (or hours, depending on the patches)

##### ACTUAL RESULTS
Update task fails with the following output:

```
{
    "exception": "Cannot find path 'C:\\Users\\TEMP.<User>\\AppData\\Local\\Temp\\ansible-tmp-1662357895.7863846-88930-81709384284258' because it does not exist.\nAt line:1537 char:17\r\n+ $outputDirAcl = Get-Acl -LiteralPath $outputPathDir\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n    + CategoryInfo          : ObjectNotFound: (:) [Get-Acl], ItemNotFoundException\n    + FullyQualifiedErrorId : GetAcl_PathNotFound,Microsoft.PowerShell.Commands.GetAclCommand\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 1537\r\n",
    "msg": "Unhandled exception while executing module: Cannot find path 'C:\\Users\\TEMP.<User>\\AppData\\Local\\Temp\\ansible-tmp-1662357895.7863846-88930-81709384284258' because it does not exist.",
    "found_update_count": 0,
    "failed_update_count": 0,
    "installed_update_count": 0,
    "updates": {},
    "filtered_updates": {},
    "invocation": {
        "module_args": {
            "reboot_timeout": 3600,
            "category_names": [
                "CriticalUpdates",
                "SecurityUpdates",
                "UpdateRollups"
            ],
            "reboot": true,
            "server_selection": "default",
            "accept_list": null,
            "state": "installed",
            "use_scheduled_task": false,
            "reject_list": null,
            "skip_optional": false,
            "log_path": "C:/Temp/ansible-windows-update-2022-09-05.log"
        }
    },
    "_ansible_no_log": false,
    "changed": false
}

```

The user Ansible uses to connect to remote Windows server is a domain user. Looking through the Windows logs we have seen this path ( 'C:\\Users\\TEMP.<User>') belongs to a temporary profile that seems to be created because the domain user profile can't be accessed (we still don't know why). I thought this temporary profile could be causing the error, but we have seen that there are other Ansible tasks launched with temporary profiles and those don't fail (i.e. win_ping).

I can try and get more information if needed.

Thanks!

**Comment by jborean93** [comment]
The problem is certainly the temporary profile you are showing, the docs indicate this profile is cleaned up after the logon session is completed (a reboot) so the next round of updates is expecting that path to still exist as it does on a normal profile. This is not a problem with other modules because they don't persist this temp path beyond the life of a single module execution. The `win_updates` module is special because not only can it run the module internally multiple times it could also do so across reboots (where the temp profile is removed).

I'll have to think of a good way to workaround this problem as making sure you use a real profile in `TEMP` is nice to say, I'm sure in practice it's good to be resilient enough not to warrant it.

**Comment by anasaizg** [comment]
Thanks Jordan! This doesn't look as a simple thing to workaround, I appreciate you thinking about it. In the meantime let's see if we come up with some way to try this doesn't happen.

**Comment by jborean93** [comment]
I've got a fix which I think will work https://github.com/ansible-collections/ansible.windows/pull/422. I'm just trying to figure out a way to actually replicate this in the wild so I can test it properly but theoretically it should work.

**Comment by jborean93** [comment]
Was able to setup a test system that replicated the `TEMP` profile and fixed a few problems with those changes. The PR should fix this problem now.

**Comment by anasaizg** [comment]
OMG you're so fast! :) Thank you very much for your efforts, we'll test it as soon as possible!
