### ISSUE TITLE
Allow using `$Ansible.Diff` to return diff information in win_powershell module

### ISSUE THREAD

**Issue by Yannik** [ansible-collections/ansible.windows#426]
##### SUMMARY
The `win_powershell` module allows to return information via properties of the `$Ansible` variable

For example:
- `$Ansible.Changed`
- `$Ansible.Failed`

and also `$Ansible.Result`

`$Ansible.Result` can be used to return all kinds of information to ansible, including more detailed change information than `true`/`false` (which can be provided with `$Ansible.Changed`). However, this requires a separate `debug` task to actually output the information. (Or alternatively requires verbose mode to be enabled)

It would be great if a variable `$Ansible.Diff` could be used to return output which is shown when diff mode is enabled

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_powershell

**Comment by Yannik** [comment]
@jborean93 What do you think about this?

**Comment by jborean93** [comment]
For sure we can add this, it should be simple enough to add.

**Comment by jborean93** [comment]
PR for this functionality https://github.com/ansible-collections/ansible.windows/pull/438.

**Comment by Yannik** [comment]
Great, thank you @jborean93! :-)
