### ISSUE TITLE
Disks not initialized (windows 2022)

### ISSUE THREAD

**Issue by musklor** [ansible-collections/ansible.windows#440]
Hi, I have some issues with windows 2022.

Sometimes, with the windows modules, my disks are online, formated and mounted.
Sometimes, not at all. (Offline)

Configuration :
Vmtools 12.1
Os : windows 2022
VRA : 8.7

**Comment by jborean93** [comment]
Can you be more specific please, is this a problem with a module or something else?

**Comment by musklor** [comment]
Sorry wrong place
