### ISSUE TITLE
After patching via ansible the last installed updates date is not changes but the system is updated. Even after doing multiple manual reboots, it shows the old date only

### ISSUE THREAD

**Issue by Leo-hanosl** [ansible-collections/ansible.windows#444]
We still have this issue. did u find a solution to it?

_Originally posted by @Leo-hanosl in https://github.com/ansible-collections/ansible.windows/issues/187#issuecomment-1312821542_

**Comment by jborean93** [comment]
No, as mentioned in that issue we get the date from the Windows Update API and are at the mercy of what it reports. If it gives an incorrect date we have no way of knowing that.
