### ISSUE TITLE
win_service module unable to start a application service in windows server

### ISSUE THREAD

**Issue by ShyamKumar-Y** [ansible-collections/ansible.windows#445]
##### SUMMARY
We have a business application server where we are using win_service module to stop and start the services through Ansible. We are able to stop the services but unable to start it again. Sometimes it is able to start and sometimes not.

```json
{
    "username": "svc_account@domain.com",
    "description": "",
    "exists": true,
    "depended_by": [],
    "dependencies": [
        "RPCSS"
    ],
    "can_pause_and_continue": false,
    "path": "C:\\Program Files\\Liquent\\(x86)\\BusinessServiceServer.exe",
    "name": "BusinessServiceServer",
    "display_name": "BusinessServiceServer",
    "_ansible_no_log": false,
    "start_mode": "auto",
    "changed": false,
    "state": "stopped",
    "msg": "Failed to start service 'BusinessServiceServer (BusinessServiceServer)'.",
    "desktop_interact": false
}
```

##### ISSUE TYPE
Unable to start a services using win_service module

##### COMPONENT NAME
win_service

##### ANSIBLE VERSION
Ansible version: 2.9.27

##### COLLECTION VERSION
```paste below

```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
Ansible tower OS version: RHEL 7.9
Windows server: Win2019

##### STEPS TO REPRODUCE
```yaml
- hosts: ApplicationServer
  gather_facts: true
  
  tasks:
     - name: Start the Business Service server in Applicaiton server
       win_service:
         name: BusinessServiceServer
         state: started
         force_dependent_services: yes
```

##### EXPECTED RESULTS
If the job is successful, the application service should be in running state. Here is the output when job get successful

```json
{
    "username": "svc_account@domain.com",
    "description": "",
    "exists": true,
    "depended_by": [],
    "dependencies": [
        "RPCSS"
    ],
    "can_pause_and_continue": false,
    "path": "C:\\Program Files\\Liquent\\(x86)\\BusinessServiceServer.exe",
    "name": "BusinessServiceServer",
    "display_name": "BusinessServiceServer",
    "_ansible_no_log": false,
    "start_mode": "auto",
    "changed": true,
    "state": "running",
    "desktop_interact": false
}
```

##### ACTUAL RESULTS
```json
{
    "username": "svc_account@domain.com",
    "description": "",
    "exists": true,
    "depended_by": [],
    "dependencies": [
        "RPCSS"
    ],
    "can_pause_and_continue": false,
    "path": "C:\\Program Files\\Liquent\\(x86)\\BusinessServiceServer.exe",
    "name": "BusinessServiceServer",
    "display_name": "BusinessServiceServer",
    "_ansible_no_log": false,
    "start_mode": "auto",
    "changed": false,
    "state": "stopped",
    "msg": "Failed to start service 'BusinessServiceServer (BusinessServiceServer)'.",
    "desktop_interact": false
}
```

**Comment by jborean93** [comment]
Unfortuantely this isn't really something with Ansible, the code is simply calling `Start-Service` as per https://github.com/ansible-collections/ansible.windows/blob/f049245f74030c9d55838e6647e7300300e76f75/plugins/modules/win_service.ps1#L840

This is a cmdlet from Windows itself which in turn calls SCManager to start the service. If it fails to start for whatever reason then Ansible can't really do much else to work around this. You need to go onto the service and figure out from any logs why `BusinessServiceServer` fails to start. You can even try and replicate this outside of the `win_service` module by doing

```yaml
- win_shell: Start-Service -Name BusinessServiceServer
```

One thing to keep in mind is to see what other steps you might be doing around this particular task. If you are configuring it but things aren't fully settled then the service may fail to start but might work sometime later. This is where the logs come into play to try and help you figure out why it failed to start in the first place.

**Comment by ShyamKumar-Y** [comment]
Hello Jordan,

Thanks for the update. May I know where can I find the logs to check? I don't find anything on the tower, even though tis running on debug mode.

**Comment by jborean93** [comment]
It’s the windows side the logs are on. Ansible only knows it couldn’t start the service not the why unfortunately. There are generic logs on the windows event viewer for services and the service itself might be logging information as well.
