### ISSUE TITLE
Exception calling "HasExtension" with "1" argument(s): "Illegal characters in path."

### ISSUE THREAD

**Issue by tlsalex** [ansible-collections/ansible.windows#446]
##### SUMMARY

try to run 
`ansible moi -m win_command -a '{"_raw_params": "C:\PS\qianniu910.exe /S", "output_encoding_override": "gb2312"}'`
and get below error:

> Exception calling "HasExtension" with "1" argument(s): "Illegal characters in path."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_command 
##### ANSIBLE VERSION

```paste below
ansible [core 2.13.6]
  config file = /home/alex/.ansible/ansible.cfg
  configured module search path = ['/home/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/alex/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/alex/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/alex/.local/bin/ansible
  python version = 3.9.14 (main, Nov  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

AlmaLinux release 9.1 (Lime Lynx)
5.14.0-162.6.1.el9_1.x86_64

##### STEPS TO REPRODUCE

run ad hoc command 
ansible moi -m win_command -a '{"_raw_params": "C:\PS\qianniu910.exe /S", "output_encoding_override": "gb2312"}'

```yaml

```

##### EXPECTED RESULTS

my cmd execute successfully

##### ACTUAL RESULTS

Exception calling "HasExtension" with "1" argument(s): "Illegal characters in path."

```paste below

```

**Comment by tlsalex** [comment]
this is related to the original issue in ticket #363

**Comment by tlsalex** [comment]
will it be the dot in the path -- C:\PS\qianniu910.exe cause that problem?  how to escape it.

**Comment by tlsalex** [comment]
below way got the same error:

```
ansible moi -m win_command -a 'cmd=" C:\PS\qianniu910.exe /S" output_encoding_override="gb2312"'
```

**Comment by tlsalex** [comment]
but it did work with bellow playbook
```
  tasks:
    - name: test cmd
      ansible.windows.win_command:
        cmd: C:\PS\qianniu910.exe /S
        output_encoding_override: gb2312
      register: myoutput
    - name: output myoutput var
      debug:
       var: myoutput
```

**Comment by jborean93** [comment]
The problem here is that `{"_raw_params": "C:\PS\qianniu910.exe /S", "output_encoding_override": "gb2312"}` is not valid JSON as the backslashes need to be escaped. Because it isn't valid JSON then Ansible fails to parse it as module options from the json and treats the full string as the command to run which contain invalid path characters. Change it to the below and it will work

```bash
ansible moi -m win_command -a '{"_raw_params": "C:\\PS\\qianniu910.exe /S", "output_encoding_override": "gb2312"}'
```

Note you can also use `C:/PS/qianniu910.exe` for your path as Windows treats forward slashes in a similar fashion.
