### ISSUE TITLE
Exception calling "HasExtension" with "1" argument(s): "Illegal characters in path." 

### ISSUE THREAD

**Issue by tlsalex** [ansible-collections/ansible.windows#447]
##### SUMMARY

#446 is closed, but problem persist, so I create a new one
try to run 
`ansible moi -m win_command -a '{"_raw_params": "C:\PS\qianniu910.exe /S", "output_encoding_override": "gb2312"}'`
and get below error:

> Exception calling "HasExtension" with "1" argument(s): "Illegal characters in path."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_command 
##### ANSIBLE VERSION

```paste below
ansible [core 2.13.6]
  config file = /home/alex/.ansible/ansible.cfg
  configured module search path = ['/home/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/alex/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/alex/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/alex/.local/bin/ansible
  python version = 3.9.14 (main, Nov  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

AlmaLinux release 9.1 (Lime Lynx)
5.14.0-162.6.1.el9_1.x86_64

##### STEPS TO REPRODUCE

run ad hoc command 
ansible moi -m win_command -a '{"_raw_params": "C:\PS\qianniu910.exe /S", "output_encoding_override": "gb2312"}'

```yaml

```

##### EXPECTED RESULTS

my cmd execute successfully

##### ACTUAL RESULTS

Exception calling "HasExtension" with "1" argument(s): "Illegal characters in path."

```paste below

```

**Comment by tlsalex** [comment]
below way mentioned in ticket #446 did not work,

> The problem here is that {"_raw_params": "C:\PS\qianniu910.exe /S", "output_encoding_override": "gb2312"} is not valid JSON as the backslashes need to be escaped. Because it isn't valid JSON then Ansible fails to parse it as module options from the json and treats the full string as the command to run which contain invalid path characters. Change it to the below and it will work
> 
> ansible moi -m win_command -a '{"_raw_params": "C:\\PS\\qianniu910.exe /S", "output_encoding_override": "gb2312"}'
> Note you can also use C:/PS/qianniu910.exe for your path as Windows treats forward slashes in a similar fashion.

below is my try, I event try escaped with different way.

```
[alex@ans .ansible]$ ansible moi -m win_command -a '{"_raw_params": "C:\\PS\\qianniu910.exe /S", "output_encoding_override": "gb2312"}'
GZGCCPC1SGA7R.hhc.hyattdir.net | FAILED | rc=2 >>
Failed to run: '{"_raw_params": "C:\\PS\\qianniu910.exe /S", "output_encoding_override": "gb2312"}': Exception calling "HasExtension" with "1" argument(s): "Illegal characters in path."
[alex@ans .ansible]$ ansible moi -m win_command -a '{"_raw_params": "C:/PS/qianniu910.exe /S", "output_encoding_override": "gb2312"}'
GZGCCPC1SGA7R.hhc.hyattdir.net | FAILED | rc=2 >>
Failed to run: '{"_raw_params": "C:/PS/qianniu910.exe /S", "output_encoding_override": "gb2312"}': Exception calling "HasExtension" with "1" argument(s): "Illegal characters in path."
[alex@ans .ansible]$ ansible moi -m win_command -a '{"_raw_params": "C:/PS/qianniu910.exe", "output_encoding_override": "gb2312"}'
GZGCCPC1SGA7R.hhc.hyattdir.net | FAILED | rc=2 >>
Failed to run: '{"_raw_params": "C:/PS/qianniu910.exe", "output_encoding_override": "gb2312"}': Exception calling "HasExtension" with "1" argument(s): "Illegal characters in path."
[alex@ans .ansible]$ ansible moi -m win_command -a '{"_raw_params": "C:\\PS\\qianniu910.exe", "output_encoding_override": "gb2312"}'
GZGCCPC1SGA7R.hhc.hyattdir.net | FAILED | rc=2 >>
Failed to run: '{"_raw_params": "C:\\PS\\qianniu910.exe", "output_encoding_override": "gb2312"}': Exception calling "HasExtension" with "1" argument(s): "Illegal characters in path."
[alex@ans .ansible]$ ansible moi -m win_command -a 'hostname'
myfqdn.xx.net | CHANGED | rc=0 >>
myfqdn
```

**Comment by jborean93** [comment]
That's also because you don't have a new enough Ansible version. The feature that allowed `-a` to accept raw json as module options was added with https://github.com/ansible/ansible/pull/78114 and is only present in Ansible 2.14+ (not Ansible 2.13). See it under minor changes of the release notes https://github.com/ansible/ansible/blob/v2.14.0/changelogs/CHANGELOG-v2.14.rst#minor-changes.

This won't be backported as it's a new feature not a bugfix.
