### ISSUE TITLE
Module win_wait_for does not work. Function name and call for function are different. 

### ISSUE THREAD

**Issue by SonnDrake** [ansible-collections/ansible.windows#451]
Hello.

Function name and call for function are different. Module does not work.

https://github.com/ansible-collections/ansible.windows/blob/main/plugins/modules/win_wait_for.ps1#L81
Function Get-PortConnection($hostname, $port)

https://github.com/ansible-collections/ansible.windows/blob/f049245f74030c9d55838e6647e7300300e76f75/plugins/modules/win_wait_for.ps1#L230

$active_connections = Get-PortConnections -hostname $hostname -port $port

**Comment by jborean93** [comment]
Sorry for the delay, https://github.com/ansible-collections/ansible.windows/pull/458 fixes this problem. Thanks for reporting the issue.
