### ISSUE TITLE
Windows modules not working with Windows server 2022

### ISSUE THREAD

**Issue by musklor** [ansible-collections/ansible.windows#465]
When we use win_format, win_initialize_disk, win_partition, we have some random issues with windows server 2022.

No issues with Windows 2019.

Test :
- latest ISO windows 2022 (october)
- VRA manage ansible
- tls 1.3 disabled -> No more chance

**Comment by jborean93** [comment]
These are all modules in the [community.windows](https://github.com/ansible-collections/community.windows). If reporting an issue there please provide more information such as what you are trying to run, what are the errors.
