### ISSUE TITLE
invalid literal for int() with base 10: win_updates

### ISSUE THREAD

**Issue by Rez0k** [ansible-collections/ansible.windows#477]
Hi,

I am trying to run automatic windows updates on my aws ec2 instances with this plugin.

the error:
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 760, in run
    result = self._run_sync(task_vars, module_options, reboot, reboot_timeout)
  File "/usr/local/lib/python3.9/dist-packages/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 834, in _run_sync
    update_result = self._run_updates(task_vars, module_options, poll_script_path, cancel_script_path)
  File "/usr/local/lib/python3.9/dist-packages/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 931, in _run_updates
    entries, offset = self._poll_result(poll_script_path, output_path, offset)
  File "/usr/local/lib/python3.9/dist-packages/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 987, in _poll_result
    offset = int(lines.pop(-1))
ValueError: invalid literal for int() with base 10: '{"task":"search_result","result":{"updates":[],"filtered":[]}}{"task":"exit","result":{"action":null,"exception":null,"reboot_required":false,"failed":false,"changed":false}}178'
fatal: [***]: FAILED! => {
    "changed": false,
    "failed_update_count": 0,
    "filtered_updates": {},
    "found_update_count": 0,
    "installed_update_count": 0,
    "invocation": {
        "module_args": {
            "accept_list": null,
            "category_names": [
                "SecurityUpdates",
                "CriticalUpdates",
                "UpdateRollups"
            ],
            "log_path": null,
            "reboot": true,
            "reboot_timeout": 1200,
            "reject_list": null,
            "server_selection": "default",
            "skip_optional": false,
            "state": "installed",
            "use_scheduled_task": false
        }
    },
    "msg": "invalid literal for int() with base 10: '{\"task\":\"search_result\",\"result\":{\"updates\":[],\"filtered\":[]}}{\"task\":\"exit\",\"result\":{\"action\":null,\"exception\":null,\"reboot_required\":false,\"failed\":false,\"changed\":false}}178'",
    "updates": {}
}
```

I don't know why this is failing here 
https://github.com/ansible-collections/ansible.windows/blob/main/plugins/action/win_updates.py#L987

my task:
```
- name: "Install all updates and reboot as many times as needed"
   ansible.windows.win_updates:
     category_names: '*'
     reboot: yes
```

ansible version:
```
ansible [core 2.14.2]
  config file = None
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Comment by jborean93** [comment]
Sorry I haven't replied earlier. Are you able to share what connection plugin you are using to connect to Ansible? Are you seeing this regularly, is it common to specific servers or any other information that might be helpful to share?

The problem here is that the output this is parsing should have a newline between the json output and the final offset int value but in your error message there is no newline.

**Comment by Rez0k** [comment]
> Sorry I haven't replied earlier. Are you able to share what connection plugin you are using to connect to Ansible? Are you seeing this regularly, is it common to specific servers or any other information that might be helpful to share?
> 
> The problem here is that the output this is parsing should have a newline between the json output and the final offset int value but in your error message there is no newline.

I am using the aws ssm plugin
https://docs.ansible.com/ansible/latest/collections/community/aws/aws_ssm_connection.html

**Comment by jborean93** [comment]
The PR https://github.com/ansible-collections/ansible.windows/pull/491 should help improve this situation for you but I cannot guarantee that `aws_ssm` won't do anything else with the output that could break other things. The PR will at least be more defensive with this particular scenario and allow it to work.
