### ISSUE TITLE
RFE: "rebooted" return value for win_updates

### ISSUE THREAD

**Issue by hiyokotaisa** [ansible-collections/ansible.windows#485]
##### SUMMARY

Currently win_updates module has no return value to identify managed windows nodes were rebooted or not. 

It would be great if we can have return value like `rebooted` boolean to check the status of windows node.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_updates

##### ADDITIONAL INFORMATION

We can check uptime of windows nodes to verify the host has been rebooted but return value is simpler way.

**Comment by jborean93** [comment]
This has been implemented with https://github.com/ansible-collections/ansible.windows/pull/493.
