### ISSUE TITLE
The error was: winrm.exceptions.WinRMTransportError: Bad HTTP response returned from server. Code 400

### ISSUE THREAD

**Issue by shivamaheskumar** [ansible-collections/ansible.windows#504]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: winrm.exceptions.WinRMTransportError: Bad HTTP response returned from server. Code 400
fatal: [127.0.0.1]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

When am using  ansible.windows.win_powershell  module am getting above error.Any one suggest how to overcome this error.
Thanks in advance.

**Comment by mhallin2** [comment]
I have the same issue

**Comment by jborean93** [comment]
Sorry I missed this issue, can you share more info around what might code the module is running. I've seen similar issues when the network stack is being reset but knowing more will help figure out what is going on.

**Comment by mhallin2** [comment]
unfortunately unable to remember what I did to get this error or what I did to resolve it. did not document anything.

**Comment by jborean93** [comment]
Closing without seeing any more information. If we can reproduce how it's running we can reopen the issue or open a new one with the details.
