### ISSUE TITLE
Reference to microsoft.ad on docs pages

### ISSUE THREAD

**Issue by PatrickV-code** [ansible-collections/ansible.windows#551]
##### SUMMARY
On microsoft.ad there is refence to the fact various modules replace some of the ansible.windows collection modules.
For example on: https://docs.ansible.com/ansible/latest/collections/microsoft/ad/computer_module.html
It is stated: this module replaces community.windows.win_domain_computer. See the migration guide for details.
However, on the ansible.windows.win_domain_membership there is no such reference.

Would it be possible to point from the replaced modules (as per: https://docs.ansible.com/ansible/latest/collections/microsoft/ad/docsite/guide_migration.html) to the microsoft.ad collection?

Reason for asking as the for example microsoft.ad modules have reboot options, while the domain related modules in ansible.windows don't. Making them more easy to work with. However, when googling "ansible domain controller" the "old" collection shows up first causing "issues" for users.

Having this documentation pointer makes finding the microsoft.ad collection easier.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION
```
ansible [core 2.15.3]
```

**Comment by jborean93** [comment]
This is currently present it's just that the latest docs are still pointing to an older `ansible.windows` release. When the next major release of the `ansible` PyPI package goes out it'll include the `2.x.y` versions of the `ansible.windows` collections which include the deprecation message. You can see what it looks like today by checking the `devel` and not `latest` docs link https://docs.ansible.com/ansible/devel/collections/ansible/windows/win_domain_controller_module.html

![image](https://github.com/ansible-collections/ansible.windows/assets/8462645/66288119-7b4b-42a5-9921-dbe4264ac3b4)

Unfortunately until the next release comes out it'll continue to reflect the docs in the `1.x.y` versions of this collection and not the `2.x.y` ones.
