### ISSUE TITLE
Typo in Verbose Messages for Windows Updates Progress

### ISSUE THREAD

**Issue by USB-Coffee** [ansible-collections/ansible.windows#554]
##### SUMMARY
Verbose output for ansible.windows updates contains a typo for "Download".
The text says "Downlad". 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_updates.py

https://github.com/ansible-collections/ansible.windows/blob/052ef994b9ce50653fdd8a000250a78d490b0406/plugins/action/win_updates.py#L1035

##### ANSIBLE VERSION
N/A
```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
```paste below
latest ansible.windows 
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

use collection  with verbose output enabled to monitor download and installation of updates. 

```yaml
N/A
```

##### EXPECTED RESULTS

Text should state "Download" 

##### ACTUAL RESULTS

Text states "Downlad" 

```paste below
N/A
```

**Comment by jborean93** [comment]
Thanks for the report, if you get a the time it would be great if you could raise a PR, if not I'll open one when I get to it next.
