### ISSUE TITLE
Don't you think using fully qualified function names could improve speed on some modules ?

### ISSUE THREAD

**Issue by gillg** [ansible-collections/ansible.windows#577]
As a general question about perfs, because I notice very poor perfs on some modules (example to list disks, partitions, volumes, format them etc...), I'm wondering if taking habbits to use a fully qualified command name in the ps1 scripts could not help ?

Anyone having experience ? Advices ? Benchmarks ?

Example: Instead of calling `Get-Volume -DriveLetter $DriveLetter`, we could do `Storage\Get-Volume -DriveLetter $DriveLetter`
Or `Microsoft.PowerShell.Utility\Get-Date` (maybe this one is a little bit excessive...).
In theory that should save the time of fetching all the modules and searching for the function, but I'm not expert on how powershell load modules and keep and eventual cache.
By the way, calling different commands related to the same module in different tasks is also very slow as the module seems reloaded every time.

Any opinion on this subject ?
cc gurus like @jborean93 and others :)

**Comment by jborean93** [comment]
Potentially, I can't say I've come across a scenario where the fully qualified name improved the time in any noticeable way. Maybe if it is proven for an explicit scenario to actually make a difference we will accept a change that does that but I would err on the side of simplicity and maintainability to avoid it in general.

The typical bulk of the runtime today is more around setting up the connection, copying across the code to run for each invocation. These are fundamental problems in how Ansible works today and while we have some ideas on how to potentially improve it they are really just ideas at this point in time.

**Comment by jborean93** [comment]
Closing as per the above.
