### ISSUE TITLE
Using "delegate_to" with ansible.windows.win_uri Module

### ISSUE THREAD

**Issue by pateldm2008** [ansible-collections/ansible.windows#578]
Please raise issues via the [new interface](https://github.com/ansible/ansible/issues/new/choose)
Trying to run a Task from Ansible Node using delegate_to: 127.0.0.1 fails with host unreachable error. The idea is the run a task from Ansible Node to update results in ServiceNow Change instead of executing it from a Windows Host. 
Here is the Task from the Playbook:
      - name: Post results
        ansible.windows.win_uri:
          url: https://Servicenow.net/api/service-now/change-request/{{sys_id}}/work-notes
          method: PATCH
          headers:
            x-functions-key: "{{xauthKey}}"
            instance: "{{ snow_instance }}"
          body:
            work_notes: "{{ winaqp.content | XXXXXcode}}"
        delegate_to: 127.0.0.1

**Comment by jborean93** [comment]
`delegate_to: 127.0.0.1` is going to be localhost and `win_uri` is meant to run on a Windows host. You probably want to use `ansible.builtin.uri` not `ansible.windows.win_uri` here.

**Comment by pateldm2008** [comment]
Thank you for quick response. Let me try that.

**Comment by jborean93** [comment]
Closing as per https://github.com/ansible-collections/ansible.windows/issues/578#issuecomment-1919972994
