### ISSUE TITLE
Check for missing commits vs devel

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/ansible.windows#6]
##### SUMMARY
The "Big Migration" has now taken place.

As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created.

Please check the contents of https://github.com/ansible-collection-migration/ansible.windows against this repo

In particular:
* Please do a per-file level diff against every file in the ansible-collection-migration repo and this one
* Pay care to files added and removed.
* During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

##### ISSUE TYPE
- Bug Report

**Comment by jborean93** [comment]
I recreated this repo from there when migration was happening so this shouldn't be an issue. In any case there was no changes to the modules/tests for plugins in this repo during that freeze period.
