### ISSUE TITLE
ERROR DURING WINRM SEND INPUT - attempting to recover: WinRMTransportError Bad HTTP response returned from server. Code 413

### ISSUE THREAD

**Issue by Denilson388** [ansible-collections/ansible.windows#620]
Hello community,

I hope you are very well.

I am currently connecting to a server from ansible but I am getting this error: **[WARNING]: ERROR DURING WINRM SEND INPUT - attempting to recover: WinRMTransportError Bad HTTP response returned from server. Code 413.**

I have the ansible configuration like this:

    ansible_user: "{{ansible_user}}"
    ansible_password: "{{ansible_password}}"
    ansible_connection: "winrm"
    ansible_port: 5986
    ansible_winrm_scheme: https
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
    ansible_python_interpreter: /usr/bin/python3

I think it's because of the WINRM configuration. 

Actually I only enable HTTPS transport with port 5986. but not HTTP, this could be a reason why this error is generated?

I remain attentive to your comments, thank you very much.

**Comment by jborean93** [comment]
HTTP 413 is content too large, potentially your server has a smaller value set than what Ansible is trying to use.

+ What's the task you are running
+ What's the value of `Get-Item WSMan:\localhost\MaxEnvelopeSizekb` on your Windows host (it should be 500 or higher)

This has no bearing on HTTP or HTTPS, it's the WinRM service complaining the data it is given is too large.

**Comment by jborean93** [comment]
Closing as per the above, I can reopen the issue if more information is provided.
