### ISSUE TITLE
 win_copy module not handling an invalid path correctly.

### ISSUE THREAD

**Issue by snehald12** [ansible-collections/ansible.windows#621]
The jobs on Ansible Automation Platform fail with below error:
~~~
Cannot bind argument to parameter 'LiteralPath' because it is an empty string.\r\nAt line:443 char:32\r\n+     if (Test-Path -LiteralPath $parent_dir -PathType Leaf) {\r\n+                                ~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidData: (:) [Test-Path], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand\r\n\r\nScriptStackTrace:\r\nat <ScriptBlock>, <No file>: line 443\r\n",
  "msg": "Unhandled exception while executing module: Cannot bind argument to parameter 'LiteralPath' because it is an empty string.",
~~~

ISSUE TYPE
- Bug Report

COMPONENT NAME
win_copy module

ANSIBLE VERSION
ansible-core 2.15

 STEPS TO REPRODUCE
N/A

EXPECTED RESULTS
The win_copy module should handle invalid paths correctly.

ACTUAL RESULTS

The error in question happens due to the module trying to convert the dest value into a Windows System.IO.Path object, that for an invalid path, would become an empty value explaining the empty string error.

~~~
        $parent_dir = [System.IO.Path]::GetDirectoryName($dest)
        if (Test-Path -LiteralPath $parent_dir -PathType Leaf)
~~~

Reference:
https://github.com/ansible/ansible/blob/e64c6c1ca50d7d26a8e7747d8eb87642e767cd74/test/support/windows-integration/plugins/modules/win_copy.ps1#L106

Thanks.

**Comment by jborean93** [comment]
Sorry for the delay with the reply here, I unfortunately cannot replicate the problem as all combinations I've tried results in the error message `Illegal characters in path.`. Can you share the combination of `src` and `dest` that fails and what special chars you might be using as a test.

Just as an FYI I tried

+ Setting `src` to a file with the name `test"file` and `dest` to a directory with a trailing slash
+ Setting `dest` to a folder with `test"file` as the filename

**Comment by jborean93** [comment]
Closing due to not receiving any more information (I apologies for the delay in my request). If you find time to provide more info I can certainly reopen this issue and investigate further.
