### ISSUE TITLE
win_powershell sensitive parameters using `::new()`

### ISSUE THREAD

**Issue by rsdoherty** [ansible-collections/ansible.windows#631]
##### SUMMARY

Hey @jborean93 - thanks for implementing the `sensitive_parameters` feature in 2.4.0.

I'm trying to port some of my Ansible roles over to use it, but some of the servers in my inventory are 2012R2, which doesn't support the `::new()` method we're using here:

https://github.com/ansible-collections/ansible.windows/blob/main/plugins/modules/win_powershell.ps1#L736-L756

We can easily fix this by using the `New-Object` method instead and passing them in via argument list, but I know Ansible dropped support for 2012R2 and below in the 2.16 release.

Would you have any objections to me raising a quick PR to use the `New-Object` method for this feature?

##### ISSUE TYPE

- `::new()` method not available on Server 2012 R2

##### COMPONENT NAME

win_powershell

##### ADDITIONAL INFORMATION

No further information

**Comment by jborean93** [comment]
Sure a PR to avoid this is fine. Keep in mind as you’ve mentioned we don’t support these OS versions anymore so there’s no guarantees of future changes also not making breaking changes like this.
