### ISSUE TITLE
win_updates: not find cumulative updates but appears on GUI

### ISSUE THREAD

**Issue by Bicck** [ansible-collections/ansible.windows#638]
##### SUMMARY

I create a playbook for searching, downloading and installing updates on Windows devices. Fistrly i create a lab with win 11 evaluation whith a cumulative update in queue (kb5040527), i try to update the device with a playbook but not showing updates availables.

Then I applied the same playbook to a device win 10 pro, with five updates on queue (4 drivers and 1 cumulative). The playbook successfully applied the 4 drivers updates and 1 cumulative but the cumulative update installed it was not same has listed on play recap, unfortunately I lost the log and have 1 cumulative update in queue now (kb5040525) showing in GUI.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_updates
##### ANSIBLE VERSION

```
ansible [core 2.17.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
  ansible python module location = /root/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```# /usr/share/ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
ansible.windows                          2.4.0
```

##### CONFIGURATION

```
ansible-config [core 2.17.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
  ansible python module location = /root/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /usr/share/ansible/collections
  executable location = /usr/bin/ansible-config
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: [defaults]collections_paths option, does not fit var naming standard, use the singular form collections_path instead. This feature will be removed from ansible-core in version 2.19. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/usr/share/ansible/collections']
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts.yaml']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/usr/share/ansible']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /path/to/private_key.pem
DEFAULT_VERBOSITY(/etc/ansible/ansible.cfg) = 2
```

##### OS / ENVIRONMENT

Win 10 pro 22h2 build 19045.4651
Win 11 Enterprise eval build 2261.ni_release.220506-1250

##### STEPS TO REPRODUCE

ansible-playbook  -i /etc/ansible/hosts2.yaml  /etc/ansible/playbooks/updateswin.yaml -l computers -vvv

```
- name: Buscar atualizacoes
  hosts: computers
  tasks:
    - name: Pesquisar atualizacoes
      ansible.windows.win_updates:
        category_names:
        - CriticalUpdates
        - SecurityUpdates
        - Drivers
        - UpdateRollups
        - Updates
        - Upgrades
        - DefinitionUpdates
        - Application
        - Connectors
        - FeaturePacks
        - Guidance
        - ServicePacks
        - Tools
        state: searched
        log_path: C:\ansible_wu.txt
      become: true
      become_method: runas
      become_user: SYSTEM
      register: update_search

    - name: Exibir categorias encontradas
      debug:
        var: update_search.updates

    - name: Verificar se ha atts
      debug:
        msg: "Atualizacoes encontradas: {{ update_search.updates | length }}"

    - name: baixar att
      ansible.windows.win_updates:
        category_names:
        - CriticalUpdates
        - SecurityUpdates
        - Drivers
        - UpdateRollups
        - Updates
        - Upgrades
        - DefinitionUpdates
        - Application
        - Connectors
        - FeaturePacks
        - Guidance
        - ServicePacks
        - Tools
        state: downloaded
        log_path: C:\down_att.txt
      become: true
      become_method: runas
      become_user: SYSTEM
      register: update_download

    - name: Mostrar baixados
      debug:
        var: update_download.updates

    - name: Atualizar o PC
      win_updates:
        category_names:
        - CriticalUpdates
        - SecurityUpdates
        - Drivers
        - UpdateRollups
        - Updates
        - Upgrades
        - DefinitionUpdates
        - Application
        - Connectors
        - FeaturePacks
        - Guidance
        - ServicePacks
        - Tools
        state: installed
        reboot: true
        reboot_timeout: 1200
        log_path: C:\ansible_att.txt
      become: true
      become_method: runas
      become_user: SYSTEM
      register: update_apply

    - name: Att aplicadas
      debug:
        var: update_apply.updates

```

##### EXPECTED RESULTS

Apply all updates listed on GUI.

##### ACTUAL RESULTS

ansible-playbook  -i /etc/ansible/hosts2.yaml  /etc/ansible/playbooks/updateswin.yaml -l computers -v
ansible-playbook [core 2.17.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
  ansible python module location = /root/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: [defaults]collections_paths option, does not fit var naming standard, use the singular form collections_path instead. This feature will be removed from ansible-core in version 2.19. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
host_list declined parsing /etc/ansible/hosts2.yaml as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts2.yaml as it did not pass its verify_file() method
Parsed /etc/ansible/hosts2.yaml inventory source with yaml plugin
redirecting (type: action) ansible.builtin.win_updates to ansible.windows.win_updates
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: updateswin.yaml *******************************************************************************************************************************************************************************************************************
1 plays in /etc/ansible/playbooks/updateswin.yaml

PLAY [Buscar atualizacoes] ******************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
task path: /etc/ansible/playbooks/updateswin.yaml:1
redirecting (type: modules) ansible.builtin.setup to ansible.windows.setup
redirecting (type: modules) ansible.builtin.setup to ansible.windows.setup
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/setup.ps1
Pipelining is enabled.
<lab_win11> ESTABLISH WINRM CONNECTION FOR USER: lab-win on PORT 5986 TO lab_win11
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/setup.ps1
Pipelining is enabled.
<win_10> ESTABLISH WINRM CONNECTION FOR USER: user_win_10 on PORT 5986 TO win_10
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
ok: [lab-win]
ok: [win_10]

TASK [Pesquisar atualizacoes] ***************************************************************************************************************************************************************************************************************
task path: /etc/ansible/playbooks/updateswin.yaml:4
<lab-win> Running win_updates - round 1
<lab-win> Starting update task
<win_10> Running win_updates - round 1
<win_10> Starting update task
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
<lab_win11> ESTABLISH WINRM CONNECTION FOR USER: lab-win on PORT 5986 TO lab_win11
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
<win_10> ESTABLISH WINRM CONNECTION FOR USER: win_10 on PORT 5986 TO win_10
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
<lab-win> Starting polling for update results
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
<win_10> Starting polling for update results
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
<lab-win> Received final progress result from update task
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
ok: [lab-win] => {
    "changed": false,
    "failed_update_count": 0,
    "filtered_updates": {
        "null": {
            "categories": [
                null
            ],
            "downloaded": false,
            "filtered_reason": "category_names",
            "filtered_reasons": [
                "category_names"
            ],
            "id": null,
            "installed": false,
            "kb": [
                ""
            ],
            "title": null
        }
    },
    "found_update_count": 0,
    "installed_update_count": 0,
    "invocation": {
        "module_args": {
            "accept_list": null,
            "category_names": [
                "CriticalUpdates",
                "SecurityUpdates",
                "Drivers",
                "UpdateRollups",
                "Updates",
                "Upgrades",
                "DefinitionUpdates",
                "Application",
                "Connectors",
                "FeaturePacks",
                "Guidance",
                "ServicePacks",
                "Tools"
            ],
            "log_path": "C:\\ansible_wu.txt",
            "reboot": false,
            "reboot_timeout": 1200,
            "reject_list": null,
            "server_selection": "default",
            "skip_optional": false,
            "state": "searched"
        }
    },
    "reboot_required": false,
    "rebooted": false,
    "updates": {}
}
<win_10> Received final progress result from update task
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
ok: [win_10] => {
    "changed": false,
    "failed_update_count": 0,
    "filtered_updates": {},
    "found_update_count": 0,
    "installed_update_count": 0,
    "invocation": {
        "module_args": {
            "accept_list": null,
            "category_names": [
                "CriticalUpdates",
                "SecurityUpdates",
                "Drivers",
                "UpdateRollups",
                "Updates",
                "Upgrades",
                "DefinitionUpdates",
                "Application",
                "Connectors",
                "FeaturePacks",
                "Guidance",
                "ServicePacks",
                "Tools"
            ],
            "log_path": "C:\\ansible_wu.txt",
            "reboot": false,
            "reboot_timeout": 1200,
            "reject_list": null,
            "server_selection": "default",
            "skip_optional": false,
            "state": "searched"
        }
    },
    "reboot_required": false,
    "rebooted": false,
    "updates": {}
}

TASK [Exibir categorias encontradas] ********************************************************************************************************************************************************************************************************
task path: /etc/ansible/playbooks/updateswin.yaml:27
ok: [lab-win] => {
    "update_search.updates": {}
}
ok: [win_10] => {
    "update_search.updates": {}
}

TASK [Verificar se ha atts] *****************************************************************************************************************************************************************************************************************
task path: /etc/ansible/playbooks/updateswin.yaml:31
ok: [lab-win] => {
    "msg": "Atualizacoes encontradas: 0"
}
ok: [win_10] => {
    "msg": "Atualizacoes encontradas: 0"
}

TASK [baixar att] ***************************************************************************************************************************************************************************************************************************
task path: /etc/ansible/playbooks/updateswin.yaml:35
<lab-win> Running win_updates - round 1
<lab-win> Starting update task
<win_10> Running win_updates - round 1
<win_10> Starting update task
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
<lab_win11> ESTABLISH WINRM CONNECTION FOR USER: lab-win on PORT 5986 TO lab_win11
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
<lwin10> ESTABLISH WINRM CONNECTION FOR USER: win_10 on PORT 5986 TO win_10
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
<lab-win> Starting polling for update results
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
<win_10> Starting polling for update results
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
<lab-win> Received final progress result from update task
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
ok: [lab-win] => {
    "changed": false,
    "failed_update_count": 0,
    "filtered_updates": {
        "null": {
            "categories": [
                null
            ],
            "downloaded": false,
            "filtered_reason": "category_names",
            "filtered_reasons": [
                "category_names"
            ],
            "id": null,
            "installed": false,
            "kb": [
                ""
            ],
            "title": null
        }
    },
    "found_update_count": 0,
    "installed_update_count": 0,
    "invocation": {
        "module_args": {
            "accept_list": null,
            "category_names": [
                "CriticalUpdates",
                "SecurityUpdates",
                "Drivers",
                "UpdateRollups",
                "Updates",
                "Upgrades",
                "DefinitionUpdates",
                "Application",
                "Connectors",
                "FeaturePacks",
                "Guidance",
                "ServicePacks",
                "Tools"
            ],
            "log_path": "C:\\down_att.txt",
            "reboot": false,
            "reboot_timeout": 1200,
            "reject_list": null,
            "server_selection": "default",
            "skip_optional": false,
            "state": "downloaded"
        }
    },
    "reboot_required": false,
    "rebooted": false,
    "updates": {}
}
<win_10> Received final progress result from update task
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
ok: [win_10] => {
    "changed": false,
    "failed_update_count": 0,
    "filtered_updates": {},
    "found_update_count": 0,
    "installed_update_count": 0,
    "invocation": {
        "module_args": {
            "accept_list": null,
            "category_names": [
                "CriticalUpdates",
                "SecurityUpdates",
                "Drivers",
                "UpdateRollups",
                "Updates",
                "Upgrades",
                "DefinitionUpdates",
                "Application",
                "Connectors",
                "FeaturePacks",
                "Guidance",
                "ServicePacks",
                "Tools"
            ],
            "log_path": "C:\\down_att.txt",
            "reboot": false,
            "reboot_timeout": 1200,
            "reject_list": null,
            "server_selection": "default",
            "skip_optional": false,
            "state": "downloaded"
        }
    },
    "reboot_required": false,
    "rebooted": false,
    "updates": {}
}

TASK [Mostrar baixados] *********************************************************************************************************************************************************************************************************************
task path: /etc/ansible/playbooks/updateswin.yaml:58
ok: [lab-win] => {
    "update_download.updates": {}
}
ok: [win_10] => {
    "update_download.updates": {}
}
redirecting (type: action) ansible.builtin.win_updates to ansible.windows.win_updates

TASK [Atualizar o PC] ***********************************************************************************************************************************************************************************************************************
task path: /etc/ansible/playbooks/updateswin.yaml:62
redirecting (type: action) ansible.builtin.win_updates to ansible.windows.win_updates
redirecting (type: modules) ansible.builtin.win_updates to ansible.windows.win_updates
redirecting (type: action) ansible.builtin.win_updates to ansible.windows.win_updates
redirecting (type: action) ansible.builtin.win_updates to ansible.windows.win_updates
<lab-win> Running win_updates - round 1
<lab-win> Starting update task
redirecting (type: modules) ansible.builtin.win_updates to ansible.windows.win_updates
redirecting (type: action) ansible.builtin.win_updates to ansible.windows.win_updates
redirecting (type: action) ansible.builtin.win_updates to ansible.windows.win_updates
<win_10> Running win_updates - round 1
<win_10> Starting update task
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
<lab_win11> ESTABLISH WINRM CONNECTION FOR USER: lab-win on PORT 5986 TO lab_win11
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
<win10> ESTABLISH WINRM CONNECTION FOR USER: win_10 on PORT 5986 TO win_10
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
<lab-win> Starting polling for update results
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
<win_10> Starting polling for update results
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
<lab-win> Received final progress result from update task
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
ok: [lab-win] => {
    "changed": false,
    "failed_update_count": 0,
    "filtered_updates": {
        "null": {
            "categories": [
                null
            ],
            "downloaded": false,
            "filtered_reason": "category_names",
            "filtered_reasons": [
                "category_names"
            ],
            "id": null,
            "installed": false,
            "kb": [
                ""
            ],
            "title": null
        }
    },
    "found_update_count": 0,
    "installed_update_count": 0,
    "invocation": {
        "module_args": {
            "accept_list": null,
            "category_names": [
                "CriticalUpdates",
                "SecurityUpdates",
                "Drivers",
                "UpdateRollups",
                "Updates",
                "Upgrades",
                "DefinitionUpdates",
                "Application",
                "Connectors",
                "FeaturePacks",
                "Guidance",
                "ServicePacks",
                "Tools"
            ],
            "log_path": "C:\\ansible_att.txt",
            "reboot": true,
            "reboot_timeout": 1200,
            "reject_list": null,
            "server_selection": "default",
            "skip_optional": false,
            "state": "installed"
        }
    },
    "reboot_required": false,
    "rebooted": false,
    "updates": {}
}
<win_10> Received final progress result from update task
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_updates.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
ok: [win_10] => {
    "changed": false,
    "failed_update_count": 0,
    "filtered_updates": {},
    "found_update_count": 0,
    "installed_update_count": 0,
    "invocation": {
        "module_args": {
            "accept_list": null,
            "category_names": [
                "CriticalUpdates",
                "SecurityUpdates",
                "Drivers",
                "UpdateRollups",
                "Updates",
                "Upgrades",
                "DefinitionUpdates",
                "Application",
                "Connectors",
                "FeaturePacks",
                "Guidance",
                "ServicePacks",
                "Tools"
            ],
            "log_path": "C:\\ansible_att.txt",
            "reboot": true,
            "reboot_timeout": 1200,
            "reject_list": null,
            "server_selection": "default",
            "skip_optional": false,
            "state": "installed"
        }
    },
    "reboot_required": false,
    "rebooted": false,
    "updates": {}
}

TASK [Att aplicadas] ************************************************************************************************************************************************************************************************************************
task path: /etc/ansible/playbooks/updateswin.yaml:87
ok: [lab-win] => {
    "update_apply.updates": {}
}
ok: [win_10] => {
    "update_apply.updates": {}
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
win_10            : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
lab-win11                    : ok=8    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

##### EXTRA LOGS

```
2024-07-29 16:45:05Z pipe_server Starting to acquire WaitForConnection lock
2024-07-29 16:45:05Z pipe_server Acquired WaitForConnection lock
2024-07-29 16:45:05Z pipe_server Creating named pipe server 'Ansible.Windows.WinUpdates-9da2eb50-a585-41ff-b931-7b71dfebc540'
2024-07-29 16:45:05Z pipe_server Waiting for client to connect to pipe
2024-07-29 16:45:05Z pipe_server Client connect wait idx 0
2024-07-29 16:45:05Z pipe_server Client successfully connected to pipe
2024-07-29 16:45:05Z pipe_server Starting to release WaitForConnection lock
2024-07-29 16:45:05Z pipe_server Released WaitForConnection lock
2024-07-29 16:45:05Z pipe_server Starting pipe read
2024-07-29 16:45:06Z update_task Reboot requirement check: False
2024-07-29 16:45:06Z update_task Creating Windows Update session...
2024-07-29 16:45:06Z pipe_server Starting to acquire WriteLine lock
2024-07-29 16:45:06Z pipe_server Acquired WriteLine lock
2024-07-29 16:45:06Z pipe_server Writing to pipe server: {"task":"started","result":{}}
2024-07-29 16:45:06Z update_task Create Windows Update searcher...
2024-07-29 16:45:06Z pipe_server Writing task successful
2024-07-29 16:45:06Z pipe_server Starting to release WriteLine lock
2024-07-29 16:45:06Z pipe_server Released WriteLine lock
2024-07-29 16:45:06Z update_task Setting the Windows Update Agent source catalog...
2024-07-29 16:45:06Z update_task Search source set to 'default' (ServerSelection = 0)
2024-07-29 16:45:06Z update_task Searching for updates to install with query 'IsInstalled = 0'
2024-07-29 16:45:06Z pipe_server Pipe read returned: -1
2024-07-29 16:45:06Z pipe_server Starting to acquire WaitForConnection lock
2024-07-29 16:45:06Z pipe_server Acquired WaitForConnection lock
2024-07-29 16:45:06Z pipe_server Disposing pipe server for a new connection
2024-07-29 16:45:06Z pipe_server Creating named pipe server 'Ansible.Windows.WinUpdates-9da2eb50-a585-41ff-b931-7b71dfebc540'
2024-07-29 16:45:06Z pipe_server Waiting for client to connect to pipe
2024-07-29 16:45:11Z pipe_server Client connect wait idx 0
2024-07-29 16:45:11Z pipe_server Client successfully connected to pipe
2024-07-29 16:45:11Z pipe_server Starting to release WaitForConnection lock
2024-07-29 16:45:11Z pipe_server Released WaitForConnection lock
2024-07-29 16:45:11Z pipe_server Starting pipe read
2024-07-29 16:45:16Z update_task Found 1 updates
2024-07-29 16:45:16Z update_task Filtering found updates based on input search criteria
2024-07-29 16:45:16Z update_task Process filtering rules for
{
    "id":  null,
    "title":  null,
    "description":  null,
    "kb":  [
               "KB"
           ],
    "type":  "Unknown ",
    "deployment_action":  "Unknown ",
    "auto_select_on_websites":  null,
    "browse_only":  null,
    "revision_number":  null,
    "categories":  [
                       null
                   ],
    "is_installed":  null,
    "is_hidden":  null,
    "is_present":  null,
    "reboot_required":  null,
    "impact":  "Unknown ",
    "reboot_behaviour":  "Unknown ",
    "is_beta":  null,
    "is_downloaded":  null,
    "is_mandatory":  null,
    "is_uninstallable":  null,
    "auto_selection":  "Unknown ",
    "auto_download":  "Unknown "
}
2024-07-29 16:45:16Z update_task Skipping update  -  due to category_names
2024-07-29 16:45:16Z pipe_server Starting to acquire WriteLine lock
2024-07-29 16:45:16Z pipe_server Acquired WriteLine lock
2024-07-29 16:45:16Z pipe_server Writing to pipe server: {"task":"search_result","result":{"updates":[{"impact":"Unknown ","categories":[null],"revision_number":null,"auto_download":"Unknown ","deployment_action":"Unknown ","description":null,"title":null,"id":null,"is_beta":null,"is_present":null,"type":"Unknown ","reboot_behaviour":"Unknown ","is_downloaded":null,"auto_select_on_websites":null,"is_installed":null,"kb":["KB"],"is_uninstallable":null,"browse_only":null,"auto_selection":"Unknown ","reboot_required":null,"is_hidden":null,"is_mandatory":null}],"filtered":[{"id":null,"reasons":["category_names"]}]}}
2024-07-29 16:45:16Z pipe_server Writing task successful
2024-07-29 16:45:16Z pipe_server Starting to release WriteLine lock
2024-07-29 16:45:16Z pipe_server Released WriteLine lock
2024-07-29 16:45:16Z update_task No updates pending: exiting...
2024-07-29 16:45:16Z pipe_server Starting to acquire WriteLine lock
2024-07-29 16:45:16Z pipe_server Acquired WriteLine lock
2024-07-29 16:45:16Z pipe_server Writing to pipe server: {"task":"exit","result":{"action":null,"exception":null,"reboot_required":false,"failed":false,"changed":false}}
2024-07-29 16:45:16Z pipe_server Writing task successful
2024-07-29 16:45:16Z pipe_server Starting to release WriteLine lock
2024-07-29 16:45:16Z pipe_server Released WriteLine lock
2024-07-29 16:45:16Z pipe_server Starting to acquire WriteLine lock
2024-07-29 16:45:16Z pipe_server Acquired WriteLine lock
2024-07-29 16:45:16Z pipe_server Writing to pipe server: {"task":"exit","result":{"action":null,"exception":null,"reboot_required":false,"failed":false,"changed":false}}
2024-07-29 16:45:16Z pipe_server Pipe read returned: 1
2024-07-29 16:45:16Z pipe_server Waiting for client to acknowledge closing pipe
2024-07-29 16:45:16Z pipe_server Starting to acquire WaitForConnection lock
2024-07-29 16:45:16Z pipe_server Pipe failed to write: IOException(Pipe is broken.)
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Ansible.Windows.WinUpdates.PipeServer.WriteLine(String line)
2024-07-29 16:45:16Z pipe_server Starting to release WriteLine lock
2024-07-29 16:45:16Z pipe_server Released WriteLine lock
2024-07-29 16:45:16Z pipe_server Acquired WaitForConnection lock
2024-07-29 16:45:16Z pipe_server Disposing pipe server for a new connection
2024-07-29 16:45:16Z pipe_server Creating named pipe server 'Ansible.Windows.WinUpdates-9da2eb50-a585-41ff-b931-7b71dfebc540'
2024-07-29 16:45:16Z pipe_server Waiting for client to connect to pipe
2024-07-29 16:45:21Z pipe_server Client connect wait idx 1
2024-07-29 16:45:21Z pipe_server Starting to release WaitForConnection lock
2024-07-29 16:45:21Z pipe_server Released WaitForConnection lock
2024-07-29 16:45:21Z pipe_server Pipe reader failed with OperationCanceledException Pipe WaitForConnect was cancelled
2024-07-29 16:45:21Z pipe_server Cancellation requested, shutting down output consumer

```

**Comment by hugoelopezp** [comment]
I'm encountering a VERY similar problem with Cummulative Update Previews. Started seeing **Pipe is broken** and the JSON section with Null values in the logs as well - started around the end of June 2024. 

For now, the only thing that is relatively working around the issue is setting up some reject_list entries. Not elegant at all. Looking forward to knowing what the root cause is.

**Comment by Bicck** [comment]
@hugoelopezp 
What do you listed in reject list? Please share an example.

**Comment by hugoelopezp** [comment]
> @hugoelopezp 
> 
> What do you listed in reject list? Please share an example.

Because the problem specific to my case is with Preview updates, I'm just having these skipped for now. The reject_list regex entry is ".*Preview.*".

**Comment by jborean93** [comment]
The `win_updates` module uses the [COM API from Microsoft](https://learn.microsoft.com/en-us/windows/win32/api/_wua/) to drive searching, downloading, installing, and retrieving the status of updates. Unfortunately it seems like there can be a disconnect between the update installed by `win_updates` and what is shown by the GUI and vice versa. Unfortunately this means there can be a disconnect between what is installed from the GUI and the COM API but it eventually rectifies itself. There is no API I know off that can force these to sync and the COM API is the only way to drive Windows Updates through a script so we are at the mercy of what the COM API can do.

The `Pipe failed to write: ...` message is mostly for diagnostic purposes. The actual code is inside a loop so will retry trying to write the same line as it waits for Ansible to reconnect to retrieve the status line. If you are seeing a different error please open a new issue with the details, including the `log_path` result.
