### ISSUE TITLE
Finding a static file bundled with a collection from an action_plugin in said collection

### ISSUE THREAD

**Issue by jantari** [ansible-collections/ansible.windows#659]
##### SUMMARY

Hey,

I am building an ansible collection for use on Windows hosts that carries out tasks relating to a particular piece of software.

I have the need to bundle a static asset / file with that collection and copy it from the ansible controller to the target Windows host before I can execute certain modules in the collection. It's a DLL file dependency of the module scripts.

I know it's possible to use an action or action_plugin in a collection to call a module such as win_copy to achieve this, I have researched the following links and built an almost-working action:

- https://groups.google.com/g/ansible-devel/c/0eHIlgMeqqI
- https://github.com/hangsu-ma/ansible-template/blob/master/action_plugins/hello-world.py
- https://stackoverflow.com/questions/76669805/is-it-possible-to-use-an-ansible-core-module-within-a-custom-module
- https://github.com/ansible-collections/ansible.windows/blob/main/plugins/action/win_template.py
- https://demengel.net/2015/01/20/ansible-modules-and-action-plugins/
- https://github.com/ansible-collections/community.windows/blob/main/plugins/action/win_pssession_configuration.py

However what I cannot figure out is how to make ansible find the DLL source file for my

```python
copy_action = self._shared_loader_obj.action_loader.get('ansible.windows.win_copy',
                                                         ... )
```

call. I created a "files" subdirectory inside the collections' directory for my DLL. I realize this path is non-standard but there appears to be no standard way to bundle static dependencies with a collection. This is my folder structure:

```
❯ tree -L 2
.
├── README.md
├── docs
├── files
│   └── mylib.dll
├── galaxy.yml
├── meta
│   └── runtime.yml
├── plugins
│   ├── README.md
│   ├── action
│   ├── module_utils
│   └── modules
└── roles
```

Problem:

When I try to use `self._find_needle('files', 'mylib.dll')` API and call this collection from a playbook, only the directories of a role that also uses this collection and of the playbook itself are searched - NOT the collections' own directory.

When I try to use `collectiondir = self._loader.get_basedir()` or `collectiondir = os.getcwd()` and `os.path.join(collectiondir, 'files', 'mylib.dll')` it resolves to the playbooks' directory only, NOT the collections' root directory.

So I cannot get the action / action_plugin to find a file relative to itself, but I'm sure there's a way.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

action_plugins

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.11]
  config file = None
  configured module search path = ['/home/jantari/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jantari/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/jantari/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jantari/.local/bin/ansible
  python version = 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Comment by jantari** [comment]
@jborean93 hey, almost every time I've researched a tricky ansible problem you're the one who provided the insight and answer I needed, whether on GitHub or on reddit. I'm really trying to get this working soon, if you could take a look at this I'd be very grateful 🙏

**Comment by jborean93** [comment]
Thanks to @nitzmahone for pointing me in this direction.

You can use [importlib.resources](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.as_file) to interact with files inside a collection. This is the underlying API that collections use and they are set up so the paths inside a collection are treated as resources in the collection namespace.

Here is an example of how you can use it inside an action plugin to reference the file `plugins/plugin_utils/test.dll`:

```python
from __future__ import annotations

import base64
import importlib.resources

from ansible.plugins.action import ActionBase


class ActionModule(ActionBase):

    def run(self, tmp: str | None = None, task_vars: dict | None = None):
        super(ActionModule, self).run(tmp, task_vars)
        del tmp  # tmp no longer has any effect
        task_vars = task_vars or {}

        # Using absolute import path.
        # plugin_utils = importlib.resources.files('ansible_collections.ansible.windows.plugins.plugin_utils')
        # test_dll = plugin_utils / 'test.dll'

        # Using relative import path from the action plugin
        this_plugin = importlib.resources.files()
        test_dll = this_plugin / '..' / 'plugin_utils' / 'test.dll'

        # Resolve the path, useful when using a relative path
        with importlib.resources.as_file(test_dll) as file:
            # Read the file as text, a dll will probably need
            # read_bytes() instead.
            # Can also use test_dll.read_text()
            dll_content = file.read_text()

            # Can also do str(test_dll) but that will not resolve relative
            # paths.
            dll_path = str(file.resolve())

        return {
            'changed': False,
            'path': dll_path,
            'content': dll_content,
        }
```

There's a whole bunch of APIs in `importlib.resources`, some have been deprecated and some are only available in specific Python versions so what you use is up to your use case.

**Comment by jantari** [comment]
Thank you very much, I was able to get it working as an `action_plugin` like this:

```python
import importlib.resources

# ... truncated ...

new_task = self._task.copy()

this_plugin = importlib.resources.files(__package__)
dependency_dll = this_plugin / '..' / '..' / 'files' / 'mylib.dll'

with importlib.resources.as_file(dependency_dll) as file:
    dll_path = str(file.resolve())

new_task.args.update(
    dict(
        src=dll_path,
        dest=dest,
    ),
)
copy_action = self._shared_loader_obj.action_loader.get('ansible.windows.win_copy',
                                                         task=new_task,
                                                         # ... truncated ...
                                                         )

# ... truncated ...
```

Answered and solved.
