### ISSUE TITLE
Feature request: ansible_os_install_date fact

### ISSUE THREAD

**Issue by Yannik** [ansible-collections/ansible.windows#663]
##### SUMMARY
I would really appreciate having a `ansible_os_install_date` fact. Managing more than 200 win servers with ansible, things sometimes need to be rolled out to newer servers first, before applying these changes to the older ones.

The OS Install date can be determined with: 
`Get-CimInstance Win32_OperatingSystem |Select-Object -ExpandProperty InstallDate`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
setup

**Comment by jborean93** [comment]
Does this fact exist in another location like the registry. We are trying to avoid adding any extra calls to WMI/CIM because it slows the overall module down and non-admins cannot access this information.

**Comment by Yannik** [comment]
@jborean93 Using `InstallTime` registry value seems good to me.

**Comment by Yannik** [comment]
Thank you! :-)
