### ISSUE TITLE
Ansible lint - fix integration tests in order to align with ansible lint policy  

### ISSUE THREAD

**Issue by ronger4** [ansible-collections/ansible.windows#671]
##### SUMMARY

Currently when running ansible-lint command, there are many comments.
If we consider running ansible-lint as part of the CI in the future, we would like to align with ansible-lint and clean the code in order to get clean results from it. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

We need to run, check and fix ansible-lint warnings coming from all the targets.
For example:
win_acl
win_async
....

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.4]
```

##### COLLECTION VERSION

```paste below
2.5.0
```

##### STEPS TO REPRODUCE

```yaml
No special hardware needed. Will reproduce when ansible-lint runs.
```

##### EXPECTED RESULTS

Expected result after running ansible-lint would be:
![image](https://github.com/user-attachments/assets/70dce773-11da-4c67-b4a4-2aeebed159e5)

##### ACTUAL RESULTS

Running ansible-lint from .ansible/collections/ansible_collections/ansible/windows/tests/integration/targets/win_acl :
Finishes the run with the following
![image](https://github.com/user-attachments/assets/1015fc15-a1e5-4d72-b0eb-9b198477396c)

```paste below

```

**Comment by ronger4** [comment]
This issue is created so we can create small PRs and reference this issue.
Placing all changes in 1 PR for all the targets would be too large.

**Comment by jborean93** [comment]
We decided internally not to move forward with this as a certified collection does not need to enforce the linting checks on the testing files for certification and doing so causes more overhead for creating and maintaining tests.
