### ISSUE TITLE
FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Cannot open Service Control Manager on computer '.'. This operation might require other privileges."}

### ISSUE THREAD

**Issue by Denilson388** [ansible-collections/ansible.windows#692]
##### SUMMARY
Hello community, 
I hope you are all very well.

I am new to implementing ansible technology on Windows servers. What I am looking for is to create a playbook that brings me all the automatic services of my Windows server. But I am encountering this error.

##### ISSUE TYPE
-  FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Cannot open Service Control Manager on computer '.'. This operation might require other privileges."}

##### ANSIBLE VERSION

ansible [core 2.16.8]

##### CONFIGURATION

This is my ansible configuration:

ansible_connection="winrm"
ansible_winrm_server_cert_validation="ignore"
ansible_port="5986"
ansible_winrm_transport="ntlm"
ansible_user="Annsible"
ansible_password= "******"

The ansible server successfully connects to the windows server. Additionally the user that is used does not have administrator permissions on the windows machine, but is in the group: Remote Management Users. According to what I read this group allows them to be listed, modified, etc. The services of a Windows O.S.

But it generates the error and I do not know what to do.

Could someone give me some help?

I will be attentive to your comments. thank you!

**Comment by mwtrigg** [comment]
Use an administrative user, or update the ACL on the service control manager.

This is not an ansible issue.

The default ACL of the Service Control Manager in Windows does not allow for access by Remote Management Users.  You can access WMI remotely in this group, but that does not extend to the Service Control Manager.

You can review the DACL of the SCM by running 'sc.exe sdshow scmanager'

**Comment by jborean93** [comment]
Like @mwtrigg  says you can add a user to the `Remote Management Users` group which may allow you to connect to the Windows host but there will still be access checks applied to the logon session for that user depending on what you want to do. In this case you'll need to modify the ACLs for SCManager to allow non-admins to access it on a network connection and potentially even to the service itself that you wish to manage. I believe we require the `SC_MANAGER_CONNECT` right for accessing a service. It may require more if you are creating one.
