### ISSUE TITLE
win_chocolatey fails after update to v2.4.0

### ISSUE THREAD

**Issue by Outek** [ansible-collections/ansible.windows#696]
##### SUMMARY
We have plans, to upgrade chocolatey(free version) to version the latest version v2.4.0, which was released last week.
Some playbooks now have errors with the new version, but if i downgrade to v2.2.2, everything is wokring fine again. If i try the command(choco upgrade/install packagename) manually, everything is working fine too.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_chocolatey 

##### ANSIBLE VERSION

```paste below
/data # ansible --version
ansible [core 2.17.5]
  config file = /data/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.7 (main, Oct  7 2024, 11:30:19) [GCC 13.2.1 20240309] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
/data # ansible-galaxy collection list

# /usr/lib/python3.12/site-packages/ansible_collections
Collection                               Version
---------------------------------------- -------

ansible.utils                            4.1.0  
ansible.windows                          2.5.0  
community.windows                        2.3.0 
```

##### OS / ENVIRONMENT
target OS: Windows Server 2022/25, Windows 11
Connection with SSH from ansible within a docker image

##### STEPS TO REPRODUCE
Check with Chocolatey 2.2.2, and rerun test after upgrade to 2.4.0
```yaml
    - name: Install or update chocholatey package packagename
      chocolatey.chocolatey.win_chocolatey:
        name: packagename
        pinned: no
        state: latest
        source: https://artifactory/api/nuget/windows-nuget-local
```

##### EXPECTED RESULTS
The package is already installed with the latest version and no error is expected.

##### ACTUAL RESULTS
```txt
fatal: [servername]: FAILED! => {
    "changed": false,
    "choco_cli_version": "2.4.0",
    "command": "C:\\ProgramData\\chocolatey\\bin\\choco.exe upgrade packagename --fail-on-unfound --yes --no-progress --source https://artifactory/api/nuget/windows-nuget-local --timeout 2700",
    "invocation": {
        "module_args": {
            "allow_empty_checksums": false,
            "allow_multiple": false,
            "allow_prerelease": false,
            "architecture": "default",
            "bootstrap_script": null,
            "bootstrap_tls_version": [
                "tls12",
                "tls13"
            ],
            "checksum": null,
            "checksum64": null,
            "checksum_type": null,
            "checksum_type64": null,
            "choco_args": null,
            "force": false,
            "ignore_checksums": false,
            "ignore_dependencies": false,
            "install_args": null,
            "name": [
                "packagename"
            ],
            "override_args": false,
            "package_params": null,
            "pinned": false,
            "proxy_password": null,
            "proxy_url": null,
            "proxy_username": null,
            "remove_dependencies": false,
            "skip_scripts": false,
            "source": "https://artifactory/api/nuget/windows-nuget-local",
            "source_password": null,
            "source_username": null,
            "state": "latest",
            "timeout": 2700,
            "validate_certs": true,
            "version": null
        }
    },
    "msg": "Error updating package(s) 'packagename'",
    "rc": 2,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Chocolatey v2.4.0\r\nUpgrading the following packages:\r\npackagename\r\nBy upgrading, you accept licenses for the packages.\r\npackagename v1.1.10 is the latest version available based on your source(s).\r\n\r\nChocolatey upgraded 0/1 packages. \r\n See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).\r\n",
    "stdout_lines": [
        "Chocolatey v2.4.0",
        "Upgrading the following packages:",
        "packagename",
        "By upgrading, you accept licenses for the packages.",
        "packagename v1.1.10 is the latest version available based on your source(s).",
        "",
        "Chocolatey upgraded 0/1 packages. ",
        " See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log)."
    ]
}
```

**Comment by jborean93** [comment]
The `win_chocolatey` module lives in the [chocolatey.chocolatey](https://github.com/chocolatey/chocolatey-ansible) collection and issues need to be reported there sorry. At a guess the newer Chocolatey versions has changed so that when updating a package but it is already on the latest it will return an rc of 2 which the module isn't equipped to handle.

**Comment by gep13** [comment]
This question was re-asked here:

https://github.com/chocolatey/chocolatey-ansible/issues/168

But I wanted to follow up here as well.

> @jborean93 said...
At a guess the newer Chocolatey versions has changed so that when updating a package but it is already on the latest it will return an rc of 2

This is exactly what happened.  In [Chocolatey CLI 2.3.0](https://docs.chocolatey.org/en-us/choco/release-notes/#v2.3.0), we expanded the functionality of the `useEnhancedExitCodes` feature, to return different exit codes for different situations.  This feature is not enabled by default, but rather something that is opted into.

> @jborean93 said...
which the module isn't equipped to handle.

Can you elaborate on this?  Is it possible to handle these additional exit codes in Ansible itself, or is this something that needs to be added/handled in the Chocolatey module?  If the latter, is it possible you can point me at some documentation around what needs to be done?  Thanks!

**Comment by jborean93** [comment]
> Can you elaborate on this? Is it possible to handle these additional exit codes in Ansible itself, or is this something that needs to be added/handled in the Chocolatey module? If the latter, is it possible you can point me at some documentation around what needs to be done? Thanks!

It looks like the current code is checking a few different exit codes when considering if there was a successful run

https://github.com/chocolatey/chocolatey-ansible/blob/981a9677b6ca07a5b0bc668c9f4410453ca54342/chocolatey/plugins/module_utils/Packages.psm1#L702-L709

The same is in the install function

https://github.com/chocolatey/chocolatey-ansible/blob/981a9677b6ca07a5b0bc668c9f4410453ca54342/chocolatey/plugins/module_utils/Packages.psm1#L894-L901

Right now the only exit codes which are considered a success are `0, 1605, 1614, 1641, 3010`

https://github.com/chocolatey/chocolatey-ansible/blob/981a9677b6ca07a5b0bc668c9f4410453ca54342/chocolatey/plugins/module_utils/Packages.psm1#L8

It sounds like you'll need to make a change that treats `2` and any other new exit codes that can be returned by `choco.exe` with `useEnhancedExitCodes` and fix the check so it isn't considered a failure. The tricky bit is probably only ignoring those if the feature is enabled to preserve the existing checks when it is not but you know your software better than I do here :)

**Comment by gep13** [comment]
@jborean93 thank you for this.  I will discuss with the team about how we would like to proceed with this.
