### ISSUE TITLE
win_user_right: "RemovePrivilege with 2 argument(s): The request is not supported"

### ISSUE THREAD

**Issue by egvghost** [ansible-collections/ansible.windows#86]
##### SUMMARY

- win_user_right fails while trying to 'set' assignments on SeCreateGlobalPrivilege.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- win_user_right
##### ANSIBLE VERSION

```
ansible 2.9.2
  config file = None
  configured module search path = [u'/Users/egvidal/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/egvidal/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/egvidal/Library/Python/2.7/bin/ansible
  python version = 2.7.16 (default, Jul  5 2020, 02:24:03) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.21) (-macos10.15-objc-
```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT

- target OS: Windows Server 2012 Standard
- host OS: MacOS Catalina v10.15.6

##### STEPS TO REPRODUCE

- Having the SeCreateGlobalPrivilege security group with current assignment for NT AUTHORITY\LOCAL SERVICE, NT AUTHORITY\NETWORK SERVICE, BUILTIN\Administrators
- Restrict the assignment via win_user_right -> set, to only BUILTIN\Administrators, NT AUTHORITY\LOCAL SERVICE

```
policy_name: "SeCreateGlobalPrivilege"
desired_value: "BUILTIN\\Administrators|NT AUTHORITY\\LOCAL SERVICE"
desired_action: set
```
```
    win_user_right:
      name: "{{ policy_name }}"
      users: "{{ desired_value.split('|') }}"
      action: "{{ desired_action }}"
```

##### EXPECTED RESULTS

- Replace the existing assignment (NT AUTHORITY\LOCAL SERVICE, NT AUTHORITY\NETWORK SERVICE, BUILTIN\Administrators) with the one required (BUILTIN\Administrators, NT AUTHORITY\LOCAL SERVICE)
- It works perfectly on this other task (having as current assignment NT AUTHORITY\LOCAL SERVICE, BUILTIN\Administrators, NT AUTHORITY\NETWORK SERVICE):

```
policy_name: "SeTimeZonePrivilege"
desired_value: "BUILTIN\\Administrators|NT AUTHORITY\\LOCAL SERVICE"
desired_action: set
```
```
    win_user_right:
      name: "{{ policy_name }}"
      users: "{{ desired_value.split('|') }}"
      action: "{{ desired_action }}"
```

##### ACTUAL RESULTS

- No change was made and an error was reported on module ps1 script execution

```
Using module file /Users/egvidal/Library/Python/2.7/lib/python/site-packages/ansible/modules/windows/win_user_right.ps1
Pipelining is enabled.
<192.168.0.12> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 192.168.0.12
EXEC (via pipeline wrapper)
The full traceback is:
Exception calling "RemovePrivilege" with "2" argument(s): "The request is not supported"
At line:320 char:13
+             $lsa_helper.RemovePrivilege($user, $name)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : Win32Exception

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 320

fatal: [w2k12]: FAILED! => {
    "changed": false, 
    "msg": "Unhandled exception while executing module: Exception calling \"RemovePrivilege\" with \"2\" argument(s): \"The request is not supported\""
}
```

**Comment by jborean93** [comment]
That's interesting, `RemovePrivilege` ends up calling [LsaRemoveAccountRights](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-lsaremoveaccountrights). The [default values](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-global-objects#default-values) for `SeCreateGlobalPrivilege` indicate the following 4 accounts are set for this right

* BUILTIN\Administrators
* NT AUTHORITY\Local Service
* NT AUTHORITY\Network Service
* NT AUTHORITY\Service

Based on your example it should be trying to remove `Network Service` and `Service` and one of those is failing. Luckily I can replicate this locally so I'll need to play around a bit more and figure out what may be happening here.

**Comment by jborean93** [comment]
After further testing I think this is one of those cases where Windows does not allow you to remove certain accounts from a privilege. I've tried to remove `NT AUTHORITY\Network Service` from either `Create global objects (SeCreateGlobalPrivilege)` or `Adjust memory quota for a process (SeIncreaseQuotaPrivilege)` from the UI with `gpedit.msc`. While it doesn't actually display any errors and seems like the accounts are removed, as soon as I close and re-open `gpedit.msc` the account is back there like it was never removed.

Are you also able to validate that's the case on your host by trying to remove `Network Service` from the privilege you are trying to remove in your task?

It probably would be a good idea to improve the error message to include the privilege(s) it was trying to remove though so I'll keep this issue opened until that is implemented.

**Comment by egvghost** [comment]
@jborean93 you are right, Windows adds Network Service again every time.. so I guess that's the issue. The OS doesn't like PS to remove that privilege. I will make a few more tests, but probably that's what's this is all about..

Thanks for your time.

**Comment by jborean93** [comment]
So while it doesn't fix the issue, which we can do nothing about, https://github.com/ansible-collections/ansible.windows/pull/91 has been merged which changes the error message in this scenario to now become

```
TASK [win_user_right] ********************************************************************************************************
task path: /home/jborean/dev/ansible-tester/main.yml:5
redirecting (type: modules) ansible.builtin.win_user_right to ansible.windows.win_user_right
Using module file /home/jborean/dev/ansible_collections/ansible/windows/plugins/modules/win_user_right.ps1
Pipelining is enabled.
<server2019.domain.local> ESTABLISH PSRP CONNECTION FOR USER: vagrant-domain@DOMAIN.LOCAL ON PORT 5985 TO server2019.domain.local
PSRP: EXEC (via pipeline wrapper)
The full traceback is:
The request is not supported
At line:396 char:13
+             $lsaHelper.RemovePrivilege($sid, $name)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], Win32Exception
    + FullyQualifiedErrorId : Win32Exception

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 396
fatal: [2019]: FAILED! => changed=false 
  added: []
  diff:
    after: ''
    before:
      SeCreateGlobalPrivilege:
      - NT AUTHORITY\SERVICE
      - BUILTIN\Administrators
      - NT AUTHORITY\NETWORK SERVICE
      - NT AUTHORITY\LOCAL SERVICE
  invocation:
    module_args:
      action: remove
      name: SeCreateGlobalPrivilege
      users:
      - Network Service
  msg: 'Failed to remove account NT AUTHORITY\NETWORK SERVICE from right SeCreateGlobalPrivilege: The request is not supported'
  removed: []
```

The error message shows the account name that was attempted to be removed and from what right.
