### ISSUE TITLE
Any option to exclude some files from delete in windows using ansible

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/ansible.windows#90]
_From @dhikrahashim on Aug 11, 2020 04:06_

##### ISSUE TYPE
- 

I want to exclude some files from deleting in windows using win_file module.
Unfortunately exclude option is there only for Linux module file, I believe.

I am getting updated application code from developer. I need to keep some files without any change in the windows application like "web.config". In that case I only need to exclude one or two files and I can replace all other files.

Other option I have is, I need to copy original "web.config" in my src folder and idempotent will work.

##### ANSIBLE VERSION

```paste below
Latest
```

##### CONFIGURATION

```
- win_find:
paths: "c:/Users/xxxx/Desktop/Newfolder/test/"
file_type: file
excludes:
 - "Global.asax"
register: found_files

- win_file:
path: "{{ item.path }}"
state: absent
with_items: "{{ found_files.files }}"
================================

- win_find:
paths: "c:/Users/farmoh/Desktop/Newfolder/test-farooq/"
file_type: file
register: found_files

- win_file:
path: "{{ item.path }}"
state: absent
with_items: "{{ found_files.files }}"
when: 'Global.asax not in item.path'

```

##### OS / ENVIRONMENT

Windows
##### ADDITIONAL INFORMATION

Tried all two types plays, nothing works

_Copied from original issue: ansible/ansible#71196_

**Comment by jborean93** [comment]
Unfortunately this isn't possible and not something I think we are interested in looking at adding. Ultimately you will have to provide your own delete logic and use a `win_shell` or `win_powershell` task to implement it.

**Comment by OneCyrus** [comment]
@jborean93 was there any specific reason why this feature gap should exists between windows and linux? or would you be open for a PR?
