### ISSUE TITLE
win_copy: Unable to copy large folder

### ISSUE THREAD

**Issue by Udayendu** [ansible-collections/ansible.windows#97]
##### SUMMARY
**win_copy** is unable to copy large folder. Max it can copy a file/directory of 2.5GiB in size. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- win_copy

##### ANSIBLE VERSION
```
# pip3 show ansible
Name: ansible
Version: 2.9.9
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.8/dist-packages
Requires: jinja2, cryptography, PyYAML
Required-by:
```

##### CONFIGURATION
- No specific configuration

##### OS / ENVIRONMENT
- Ubuntu 20.04 LTS Server

##### STEPS TO REPRODUCE
- Use the below playbook to copy a folder of 4.5 GiB in size from ansible provision server(ubuntu server) to a windows 2016 server, it will fail.
```
---
- name: Copy SQL files to Windows VM
  hosts: "{{ target }}"
  gather_facts: false
  connection: winrm

  tasks:
    - name: Copy SQL Files using win_copy module
      win_copy:
        src: /root/software/
        dest: C:\SQL2016_standard\
```

```
# tree /root/software/
/root/software/
└── SQL2016_standard
    ├── SQL2016Standardw_SP1.zip
    ├── SSMS2016_setup
    │   └── SSMS-Setup-ENU.exe
    └── updates
        ├── SQLServer2016-KB4524334-x64.exe
        └── SQLServer2016SP2-KB4052908-x64-ENU.exe
```
```
# cat inventory
[mssql]
xxx.xxx.xxx.xxx

[mssql:vars]
ansible_connection=winrm
ansible_user=global\myadmin
ansible_password=xxxxxxxxxxxxx
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
```

# Command to deploy
```
# ansible-playbook -i  inventory -e target=mssql wincp.yaml -vvv
```

##### EXPECTED RESULTS
It should copy the folder successfully.

##### ACTUAL RESULTS
Its failing with the following traces:

```
# ansible-playbook -i  inventory -e target=mssql-sentry-sql wincp.yaml -vvv
ansible-playbook 2.9.9
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
No config file found; using defaults
host_list declined parsing /root/playbooks/inventory as it did not pass its verify_file() method
script declined parsing /root/playbooks/inventory as it did not pass its verify_file() method
auto declined parsing /root/playbooks/inventory as it did not pass its verify_file() method
[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by default, this will change, but still be user configurable on deprecation. This feature will be removed in version 2.10. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Parsed /root/playbooks/inventory inventory source with ini plugin

PLAYBOOK: wincp.yaml *****************************************************************************************************************************************************************************************************************************************
1 plays in wincp.yaml

PLAY [Copy SQL files to Windows VM] **************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Copy SQL Files using win_copy module] ******************************************************************************************************************************************************************************************************************
task path: /root/playbooks/wincp.yaml:8
Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/windows/win_copy.ps1
Pipelining is enabled.
<xxx.xxx.xxx.xxx> ESTABLISH WINRM CONNECTION FOR USER: global\myadmin on PORT 5985 TO xxx.xxx.xxx.xxx
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
<xxx.xxx.xxx.xxx> PUT "/root/.ansible/tmp/ansible-local-1581142w2j6iv0m/tmphitjyjsd/win_copy.zip" TO "C:\Users\myadmin\AppData\Local\Temp\ansible-tmp-1598965263.1938927-1581146-49202896425265\source.zip"
EXEC (via pipeline wrapper)
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/winrm/protocol.py", line 248, in send_message
    root = ET.fromstring(ex.response_text)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1321, in XML
    return parser.close()
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/usr/local/lib/python3.8/dist-packages/ansible/executor/task_executor.py", line 653, in _execute
    self._handler.cleanup()
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/__init__.py", line 128, in cleanup
    self._remove_tmp_path(self._connection._shell.tmpdir)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/__init__.py", line 407, in _remove_tmp_path
    tmp_rm_res = self._low_level_execute_command(cmd, sudoable=False)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/action/__init__.py", line 1075, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/connection/winrm.py", line 548, in exec_command
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True, stdin_iterator=stdin_iterator)
  File "/usr/local/lib/python3.8/dist-packages/ansible/plugins/connection/winrm.py", line 460, in _winrm_exec
    command_id = self.protocol.run_command(self.shell_id, to_bytes(command), map(to_bytes, args), console_mode_stdin=(stdin_iterator is None))
  File "/usr/local/lib/python3.8/dist-packages/winrm/protocol.py", line 359, in run_command
    res = self.send_message(xmltodict.unparse(req))
  File "/usr/local/lib/python3.8/dist-packages/winrm/protocol.py", line 251, in send_message
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/winrm/protocol.py", line 243, in send_message
    resp = self.transport.send_message(message)
  File "/usr/local/lib/python3.8/dist-packages/winrm/transport.py", line 323, in send_message
    response = self._send_message_request(prepared_request, message)
  File "/usr/local/lib/python3.8/dist-packages/winrm/transport.py", line 339, in _send_message_request
    raise WinRMTransportError('http', ex.response.status_code, response_text)
winrm.exceptions.WinRMTransportError: Bad HTTP response returned from server. Code 400
fatal: [100.89.14.149]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************
xxx.xxx.xxx.xxx              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

**Comment by Udayendu** [comment]
I did the ansible upgrade and tried but still the same behavior. Seems some timeout is happening somewhere.

```
# pip3 show ansible
Name: ansible
Version: 2.9.13
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /usr/local/lib/python3.8/dist-packages
Requires: cryptography, jinja2, PyYAML
Required-by:
```

Also I observed that its able to make the complete tarball of the folder under /root/.ansible/tmp location but after that its not copying the data to the target location. But if the size is small then its working perfectly.

**Comment by Udayendu** [comment]
I tried to copy a single file of 6.7GiB and that worked. But when keeping that in a folder its failing with the same error.

**Comment by Udayendu** [comment]
After switching from **ntlm** to **credssp** based method, its able to do the copy from ansible provision server to windows guest system. I tried multiple size like 3GB, 5GB, 7GB and upto 8.5GB and all worked successfully.

So not sure if the issue with the module or the auth method.

**Comment by jborean93** [comment]
Hmm I can't seem to replicate this problem, I created a 4.5GB file with `fallocate -l 4.5G large.file` then ran the following playbook

```yaml
- hosts: '2019'
  gather_facts: no
  tasks:
  - win_copy:
      src: large.file
      dest: C:\temp\large.file

  - win_file:
      path: C:\temp\large.file
      state: absent
```

I made sure to use NTLM auth through WinRM based on your last comment but it succeeded in the end. Are you finding this is failing when the task starts or after some time and some data has been transferred already. Is it happening with just 1 Windows host or can you replicate it across other. When the copying is happening have you seen any large memory spikes on the Windows host that may contribute to the failure?

**Comment by Udayendu** [comment]
> Are you finding this is failing when the task starts or after some time and some data has been transferred already.

   Yes, after creating the zip file its failing. Its not able to start the copy activity.

>  Is it happening with just 1 Windows host or can you replicate it across other. 

     I tried with two systems in parallel and for both its failing at the same point with same error. And even for a single windows system also the same error at same stage. So I thought its the issue with NTLM. Because wen I am using CredSSP and WinRM, its working perfectly.

> When the copying is happening have you seen any large memory spikes on the Windows host that may contribute to the failure?
 
   No notable change in CPU & Memory utilization both at source and destination.

**Comment by jborean93** [comment]
> Yes, after creating the zip file its failing. Its not able to start the copy activity.

How long does it take before it actually fails. Is it typically once it tries to start copying the zip and it's near the end of the copy (i.e. 2+GB has been copied)?

Can you update your `ntlm-auth` and `cryptography` Python libraries and try again. Can you run that playbook (with the `fallocate` command beforehand) to see if that works for you. Can you slowly decrease the size until you find out when it starts to fail.

From my perspective I cannot replicate this problem on any of my hosts so it's going to be hard to figure out what's going wrong here. Until then there's not much I can do to try and fix the problem.

**Comment by Udayendu** [comment]
> > Yes, after creating the zip file its failing. Its not able to start the copy activity.
> 
> How long does it take before it actually fails. Is it typically once it tries to start copying the zip and it's near the end of the copy (i.e. 2+GB has been copied)?

   Usually it do create the dip properly of whatever size the actual content is. I have see it upto 8.5GiB. creating zip is never an issue. Its the copy the zip file that never worked.

> Can you update your `ntlm-auth` and `cryptography` Python libraries and try again. Can you run that playbook (with the `fallocate` command beforehand) to see if that works for you. Can you slowly decrease the size until you find out when it starts to fail.

  In my system both the packages are latest:
```
$ pip3 show ntlm-auth
Name: ntlm-auth
Version: 1.5.0
Summary: Creates NTLM authentication structures
Home-page: https://github.com/jborean93/ntlm-auth
Author: Jordan Borean
Author-email: jborean93@gmail.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires:

$ pip3 show cryptography
Name: cryptography
Version: 3.1
Summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
Home-page: https://github.com/pyca/cryptography
Author: The cryptography developers
Author-email: cryptography-dev@python.org
License: BSD or Apache License, Version 2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: cffi, six
Required-by: requests-ntlm, requests-credssp, pyspnego, paramiko, ansible
```

> From my perspective I cannot replicate this problem on any of my hosts so it's going to be hard to figure out what's going wrong here. Until then there's not much I can do to try and fix the problem.

Yes, thats true. So may be you can close this as I am no longer going to use 5985 in my platform. I am using CredSSP with 5986 and thats working perfectly.

**Comment by jborean93** [comment]
I would also be curious if the problem with NTLM over port 5985 is also an issue when you use the [psrp](https://docs.ansible.com/ansible/latest/plugins/connection/psrp.html) connection plugin. It also runs over WinRM/WSMan but in a protocol inside that with different deps.

I'm going to close the ticket for now as you've got a workaround. If you do come across any other key information please share it as we might be able to figure out what's going on from there.
